### ISSUE TITLE
Handling length 0-pages

### ISSUE THREAD

**Issue by nemojjh** [Norconex/collector-http#313] opened 2016-11-24 14:27 UTC
Hello :). Thank you.

It seems my crawler is rejecting importing documents of 0-length pages.

But I want to collect them and show in the commit result.

How can I handle this?

By using NumericMetaDataFilter and Empty? Include, field = Content-Length, eq = 0 || empty.

I tried but It didn't work.

Thank you :)

Best Regards.

**Comment by essiembre** [comment] 2016-11-24 17:02
Does it appear rejected in your logs?  Because I just tried to reproduce with the Filesystem Committer and the file was committed.  Can it be your target repository that rejects blank docs?   A copy of your config may help.

**Comment by nemojjh** [comment] 2016-11-25 00:22
`<crawlerDefaults>
		<httpClientFactory>
			<headers>
				<header name="Accept">*/*</header>
			</headers>
		</httpClientFactory>
		<userAgent>Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1;
			Trident/4.0; GTB7.4; InfoPath.2; SV1; .NET CLR 3.3.69573; WOW64)
		</userAgent>


		<delay class="com.norconex.collector.http.delay.impl.GenericDelayResolver"
			default="1500" scope="site" />
		<urlNormalizer
			class="com.norconex.collector.http.url.impl.GenericURLNormalizer">
			<normalizations>
				removeFragment, lowerCaseSchemeHost, upperCaseEscapeSequence,
				decodeUnreservedCharacters, removeDefaultPort,
				encodeNonURICharacters, removeTrailingSlash
			</normalizations>
		</urlNormalizer>
		<numThreads>10</numThreads>
		<maxDepth>3</maxDepth>
		<workDir>$workdir</workDir>
		<robotsTxt ignore="true" />
		<robotsMeta ignore="true" />
		<orphansStrategy>DELETE</orphansStrategy>

		
		
		<sitemap ignore="true" />
		
		<sitemapResolverFactory ignore="true" />

		<referenceFilters>
			<filter class="$filterExtension" onMatch="exclude">jpg,gif,png,ico,css,jpeg
			</filter>
		</referenceFilters>

		<recrawlableResolver
			class="com.norconex.collector.http.recrawl.impl.GenericRecrawlableResolver"
			sitemapSupport="never">
			<minFrequency applyTo="reference" value="900000">.*
			</minFrequency>
		</recrawlableResolver>

		<linkExtractors>
			<extractor
				class="com.norconex.collector.http.url.impl.GenericLinkExtractor"
				keepReferrerData="true">
				<tags>
					<tag name="a" attribute="href" />
					<tag name="frame" attribute="src" />
					<tag name="script" attribute="src" />
					<tag name="link" attribute="href" />
					<tag name="iframe" attribute="src" />
					<tag name="meta" attribute="http-equiv" />
					<tag name="embed" attribute="src" />
					<tag name="object" attribute="classid" />
					<tag name="object" attribute="codebase" />
					<tag name="applet" attribute="code" />
					<tag name="applet" attribute="classid" />
					<tag name="base" attribute="href" />
					<tag name="body" attribute="backgroud" />
					<tag name="area" attribute="href" />
				</tags>
			</extractor>
		</linkExtractors>


		<redirectURLProvider
			class="com.norconex.collector.http.redirect.impl.GenericRedirectURLProvider"
			fallbackCharset="utf-8" />

		<metadataFilters>
			<filter class="$filterRegexMeta" onMatch="exclude"
				caseSensitive="false" field="Content-Type">.*css.*</filter>
		</metadataFilters>
		<importer>
			<preParseHandlers>
				<tagger
					class="com.norconex.importer.handler.tagger.impl.TextPatternTagger">
					<pattern field="html_source">.*</pattern>
					<restrictTo field="document.contentType">text/html</restrictTo>
				</tagger>
				<filter class="com.norconex.importer.handler.filter.impl.ScriptFilter">
					<script><![CDATA[
            isFromIFrame = metadata.getString('collector.referrer-link-tag') == 'iframe.src';
            depth = metadata.getInt('collector.depth');
            /*return*/ (depth < 5 || isFromIFrame);
      ]]></script>
				</filter>
			</preParseHandlers>
		</importer>
	</crawlerDefaults>`

Page Structure:
 <main> ===> <subpage>
Response : 
 Connection:close
Content-Length:0
Content-Type:text/html
Date:Fri, 25 Nov 2016 00:21:35 GMT
Server:Apache

**Comment by essiembre** [comment] 2016-11-25 16:30
In the log4j.properties file, if you change the log level for REJECTED_IMPORT to DEBUG, what do you get?  It should tell you what rejected it.

**Comment by nemojjh** [comment] 2016-11-28 02:21
Deleted Code :
```
<filter class="com.norconex.importer.handler.filter.impl.ScriptFilter">
					<script><![CDATA[
            isFromIFrame = metadata.getString('collector.referrer-link-tag') == 'iframe.src';
            depth = metadata.getInt('collector.depth');
            /*return*/ (depth < 5 || isFromIFrame);
      ]]></script>
				</filter>
```

And... working fine! In my guess, Script occurred some errors.

**Comment by essiembre** [comment] 2016-11-28 16:34
Glad you have it working.  I am closing but please re-open if you do see issues with zero-length documents.

I suggest you add a [DebugTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DebugTagger.html) before your script to print the field values you are using in your script.  That may help you troubleshoot why your document is rejected.

**Closed by essiembre** 2016-11-28 16:34 UTC
