### ISSUE TITLE
Crawl behavior

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#243] opened 2016-04-20 19:07 UTC
Even with stayOnDomain="true" and maxDocuments=10 when the crawler finds a sitemap (https://www.flickr.com/sitemap/sitemap-photos-index-00000.xml) on external site it goes through all the links. Had to cancel crawl.

Am I wrong to thing stayOnDomain="true" would prevent crawling external site?

**Comment by essiembre** [comment] 2016-04-20 20:41
Yes it should stick to the domain(s) of the URL(s) you provide.  If flickr was not part of your start URLs, it should not be picked up.  Unless your sitemap itself contain an external link to flicker?  Just guessing.  Can you attach your config?

**Comment by OkkeKlein** [comment] 2016-04-20 20:44
Start is url not sitemap and only one domain. After adding referenceFilters that includes this domain it works as expected.

**Comment by essiembre** [comment] 2016-04-20 20:53
Great, but it should work without you having to do this.  It would be nice if you can share a config that reproduces the issue.

**Comment by essiembre** [comment] 2016-04-21 16:02
Thanks to the offline material you sent me, I was able to find the cause and fix it.  The latest [snapshot](https://www.norconex.com/collectors/collector-http/download) has the fix.

Please confirm.

**Comment by essiembre** [comment] 2016-06-01 15:08
@OkkeKlein: Have you had a chance to confirm this fix?  Can we close?

**Comment by essiembre** [comment] 2016-06-25 03:37
This fix was released in 2.5.0.

**Closed by essiembre** 2016-06-25 03:37 UTC
Labels: bug, fixed/done
