### ISSUE TITLE
Ampersand encoding

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#88] opened 2015-04-16 13:44 UTC
I have content with pagination and after link extraction links with &amp:amp start to show up, resulting in endless loops. The url always has the first &amp; correct, but after that it becomes messy. So it appears that a regex or something else only fixes the first occurence

**Comment by essiembre** [comment] 2015-04-17 03:48
Is it a problem with the app, or with the way URLs are generated in a page?  Do you have an example URL to reproduce this?  Recommendation: to prevent endless loops in general, make sure you specify a reasonable maximum depth.  That will ensure it gets out of the loop at some point.

**Comment by OkkeKlein** [comment] 2015-04-17 10:29
It took some time to pin this down, but I found the 2.2 snapshot downloadable on the site to have this problem. The latest code from Github or earlier versions do not show this behavior.

**Comment by OkkeKlein** [comment] 2015-04-17 13:44
The previous comment applied only to my testing scenario. Problem recurred. Will have to test more.

**Comment by OkkeKlein** [comment] 2015-04-17 15:58
Fixed it with urlnormalizer that changes &amp;amp into &amp

**Comment by essiembre** [comment] 2015-04-20 01:54
Would you say it is a problem how URLs are constructed in some of the pages being crawled?  In other words, shall we close this issue?

**Comment by OkkeKlein** [comment] 2015-04-20 08:58
I can imagine this problem surfacing on other websites. And decoding an URL before fetching can't hurt, so imo it could be standard in URL constructor.

**Comment by essiembre** [comment] 2015-04-20 15:58
What you are saying makes lots of sense, but since that issue did not surface before, I am wonder how exactly these links are found in pages. In order to ensure this issue gets resolved properly, can you attach a sample HTML file with such links, or give a URL to a page having them?

**Comment by OkkeKlein** [comment] 2015-04-21 07:00
If it didn't surface before and I can easily fix it, I think we can close the issue. Thank you.

**Comment by essiembre** [comment] 2015-04-24 04:18
I made a few tests and was able to reproduce the issue you had.  The latest [snapshot release](http://www.norconex.com/collectors/collector-http/download) has the fix.

**Comment by essiembre** [comment] 2015-07-22 18:53
Norconex HTTP Collector 2.2.0 official release is out. It includes this fix. You can download it [here](http://www.norconex.com/collectors/collector-http/download).

**Closed by essiembre** 2015-07-22 18:53 UTC
Labels: bug, fixed/done
