### ISSUE TITLE
sitemapResolverFactory is not instantiating class specified in the config

### ISSUE THREAD

**Issue by radomirml** [Norconex/collector-http#208] opened 2016-01-04 17:56 UTC
Although config reference suggests that custom sitemapResolverFactory class can be specified, looks like the class attribite is ignored and StandardSitemapResolverFactory is always used.

**Comment by essiembre** [comment] 2016-01-04 22:25
Hello Radomir!  I just tried to plug a custom implementation as a test and it worked just fine.  I tried with the latest snapshot.  Which version did you use?  There were a few regression issues introduced when changing the naming form ``<sitemap>`` to ``<sitemapResolverFactory>`` in the config.  Those have since been fixed.  I am not sure it relates to your current issue, but can you try with the latest snapshot just in case? 

If you are already using the latest snapshot, can you please attach your config so I can try to reproduce.

**Comment by radomirml** [comment] 2016-01-05 07:54
Hi Pascal, I'm using Norconex components from a Java project referencing
the following:

<dependency>
<groupId>com.norconex.collectors</groupId>
<artifactId>norconex-collector-http</artifactId>
<version>2.3.0</version>
</dependency>
<dependency>
<groupId>com.norconex.collectors</groupId>
<artifactId>norconex-collector-filesystem</artifactId>
<version>2.3.0</version>
</dependency>
<dependency>
<groupId>com.norconex.collectors</groupId>
<artifactId>norconex-importer</artifactId>
<version>2.4.0</version>
</dependency>
<dependency>
<groupId>com.norconex.collectors</groupId>
<artifactId>norconex-committer-solr</artifactId>
<version>2.0.2</version>
</dependency>

From what I could see, specified class is checked for existence (exception
is thrown if specified resolver class does not exist) but it was not
actually used.

For which module do you suggest to try snapshot? http or core?

Do you have snapshots in some public maven repo by any chance?

Thanks,
Radomir

**Comment by essiembre** [comment] 2016-01-06 21:30
For this specific issue you are describing, I would recommend the ``2.4.0-SNAPSHOT`` version of the HTTP Collector.  Snapshots are publicly released on Sonatype.  You can add that repo to your pom.xml like this:

```xml
  <repositories>
    <repository>
      <id>sonatype.oss.snapshots</id>
      <name>Sonatype OSS Snapshot Repository</name>
      <url>http://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository> 
  </repositories>
```

You do not need the ``norconex-importer`` dependency as it will be included by the collectors you already have listed.  The FileSystem Collector does not have a snapshot version containing the very latest like HTTP Collector has (it is updated more regularly).  If you think that causes you issues, let me know and I will make sure to release a snapshot compiled against the latest of its dependencies (which would be the same as HTTP Collector).

**Comment by radomirml** [comment] 2016-01-09 12:50
Using the 2.4.0-SNAPSHOT version of the HTTP Collector fixes the
sitemapResolverFactory initialization. However, I'll stay on 2.3.0 for now
as using the snapshot causes java.lang.ClassNotFoundException:
com.norconex.importer.util.CharsetUtil. I guess other components are not in
sync. As I have a workaround in place, I'll want for the official release
of the suite.

BTW, removing *norconex-importer* dependency from the pom doesn't work as
expected as I'm getting java.lang.NoSuchMethodError:
com.norconex.commons.lang.url.HttpURL.getRoot(Ljava/lang/String;)Ljava/lang/String;
Tested this with both HTTP Collector 2.3.0 and 2.4.0-SNAPSHOT.

You can close this issue.

And thanks for the great tools!

**Comment by essiembre** [comment] 2016-01-11 22:38
Humm... OK to close since you have it working for you, but snapshot releases not resolving properly for you is annoying.  They definitely should!  If you end up trying again with the snapshot version, please "force" Maven to update its dependencies in case it makes a difference and if you still have issues, please open a new ticket.   Thanks Radomir, I am glad you like the tools!

**Closed by essiembre** 2016-01-11 22:38 UTC

**Comment by radomirml** [comment] 2016-01-12 07:03
Just to clarify, I was using only snapshot of th eHTTP Collector - and that
did fix the custom sitemapResolverFactory initialization. However, the
issue appeared down the road due to some incompatibility with some other
dependency. I didn't have much time to play with it and find a cause. It
would be much easier if all components used the same version or at least to
have compatibility table. Thanks.



On Mon, Jan 11, 2016 at 11:38 PM, Pascal Essiembre <notifications@github.com
