### ISSUE TITLE
Exclude Documents with empty Document id

### ISSUE THREAD

**Issue by jerrywithaz** [Norconex/collector-http#429] opened 2017-11-20 22:28 UTC
Hi, 

I keep getting the following error when committing documents to AWS CloudSearch:

```
CloudSearch: 2017-11-20 15:15:40 INFO - Sending 10 documents to AWS CloudSearch for addition/deletion.
CloudSearch: 2017-11-20 15:15:40 ERROR - Could not commit batched operations.
com.norconex.committer.core.CommitterException: Document id cannot be empty.
	at com.norconex.committer.cloudsearch.CloudSearchCommitter.fixBadIdValue(CloudSearchCommitter.java:437)
	at com.norconex.committer.cloudsearch.CloudSearchCommitter.buildJsonDocumentAddition(CloudSearchCommitter.java:411)
	at com.norconex.committer.cloudsearch.CloudSearchCommitter.commitBatch(CloudSearchCommitter.java:339)
	at com.norconex.committer.core.AbstractBatchCommitter.commitAndCleanBatch(AbstractBatchCommitter.java:179)
	at com.norconex.committer.core.AbstractBatchCommitter.cacheOperationAndCommitIfReady(AbstractBatchCommitter.java:208)
	at com.norconex.committer.core.AbstractBatchCommitter.commitAddition(AbstractBatchCommitter.java:143)
	at com.norconex.committer.core.AbstractFileQueueCommitter.commit(AbstractFileQueueCommitter.java:222)
	at com.norconex.collector.core.crawler.AbstractCrawler.execute(AbstractCrawler.java:270)
	at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:226)
	at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:189)
	at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
	at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:355)
	at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:296)
	at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:168)
	at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:132)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:95)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
```

I am trying to use a filter to exclude empty documents in the postParseHandlers section like this:
` <filter class="com.norconex.importer.handler.filter.impl.EmptyMetadataFilter" onMatch="exclude" fields="document_id" />
`

and I tried this:

` <filter class="com.norconex.importer.handler.filter.impl.EmptyMetadataFilter" onMatch="exclude" fields="id" />
`

But, this causes all documents to get rejected. Can you provide me with some guidance on how to exclude documents with empty Document ID's? Thanks!

**Comment by essiembre** [comment] 2017-11-21 05:25
Can you share a copy of your config?  By default, the Committer takes the document reference as the id and that should never be empty.   Are you using ``<sourceReferenceField>`` in your Committer config?  If so, it should be the field you have defined there that you check for emptiness.

**Comment by jerrywithaz** [comment] 2017-11-21 14:42
Here is my config:

I don't have a sourceReferenceField defined, but I tried adding one like this: 

`<sourceReferenceField keep="true">id</sourceReferenceField>`

And it still caused all of my documents to get deleted when using:
` <filter class="com.norconex.importer.handler.filter.impl.EmptyMetadataFilter" onMatch="exclude" fields="id" />
`

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<httpcollector id="ID">

    
    <progressDir>./results/progressdir</progressDir>
    <logsDir>./results/logsDir</logsDir>

    <crawlers>
        <crawler id="Name">
            <startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
                <url>...</url>
            </startURLs>

            <workDir>./results/workDir</workDir>

            <urlNormalizer class="com.norconex.collector.http.url.impl.GenericURLNormalizer">
                <normalizations>lowerCaseSchemeHost, upperCaseEscapeSequence, decodeUnreservedCharacters, removeDefaultPort, removeFragment, removeDotSegments, removeDuplicateSlashes, removeSessionIds, upperCaseEscapeSequence</normalizations>
            </urlNormalizer>
            
            <maxDepth>100</maxDepth>
            <maxDocuments>10000</maxDocuments>
            
            <sitemapResolverFactory ignore="false"/>

            <metadataFetcher class="com.norconex.collector.http.fetch.impl.GenericMetadataFetcher">
                <validStatusCodes>200</validStatusCodes>
                <notFoundStatusCodes>404,302</notFoundStatusCodes>
            </metadataFetcher>

            <documentFetcher class="com.norconex.collector.http.fetch.impl.GenericDocumentFetcher">
                <validStatusCodes>200</validStatusCodes>
                <notFoundStatusCodes>404,302</notFoundStatusCodes>
            </documentFetcher>

            <httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
                <maxRedirects>0</maxRedirects>
            </httpClientFactory>

            <orphansStrategy>DELETE</orphansStrategy>

            <spoiledReferenceStrategizer class="com.norconex.collector.core.spoil.impl.GenericSpoiledReferenceStrategizer">
                <mapping state="NOT_FOUND" strategy="DELETE"/>
                <mapping state="BAD_STATUS" strategy="DELETE"/>
                <mapping state="ERROR" strategy="DELETE"/>
            </spoiledReferenceStrategizer>

            <delay default="1000"/>
            
            <importer>

                <preParseHandlers>
                    <filter class="com.norconex.importer.handler.filter.impl.NumericMetadataFilter" onMatch="exclude" field="docSize">
                        <condition operator="lt" number="1048575"/>
                    </filter>
                    <tagger class="com.norconex.importer.handler.tagger.impl.DocumentLengthTagger" field="docSize" />
                    <tagger class="com.norconex.importer.handler.tagger.impl.DebugTagger" logLevel="INFO"/>
                    <transformer class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer" inclusive="true" caseSensitive="false" sourceCharset="UTF-8">
                        <stripBetween>
                            <start><![CDATA[]]></start>
                            <end><![CDATA[]]></end>
                        </stripBetween>
                        <restrictTo field="document.contentType">text/html</restrictTo>
                    </transformer>
                </preParseHandlers>

                <postParseHandlers>
                    <tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
                        <fields>title,keywords,description,content,document.reference, document.contentType, collector.referrer-link-text</fields>
                    </tagger>
                    <tagger class="com.norconex.importer.handler.tagger.impl.DebugTagger" logLevel="INFO"/>
                    <tagger class="com.norconex.importer.handler.tagger.impl.ForceSingleValueTagger">
                        <singleValue field="title" action="keepFirst"/>
                    </tagger>
                    <tagger class="com.norconex.importer.handler.tagger.impl.RenameTagger">
                        <rename fromField="document.reference" toField="url" overwrite="true"/>
                        <rename fromField="document.contentType" toField="content_type" overwrite="true"/>
                        <rename fromField="collector.referrer-link-text" toField="referrer_link_text" overwrite="true"/>
                    </tagger>
                    <filter class="com.norconex.importer.handler.filter.impl.EmptyMetadataFilter" onMatch="exclude" fields="id" />
                </postParseHandlers>

            </importer>

            <referenceFilters>
                <filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter" onMatch="exclude" caseSensitive="false">
                    png,gif,jpg,jpeg,js,css,json,svg
                </filter>
                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude" caseSensitive="false">
                    .*/runtime/.*
                </filter>
                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude" caseSensitive="false">
                    .*/design/.*
                </filter>
                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude" caseSensitive="false">
                    .*/templates/.*
                </filter>
                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude" caseSensitive="false">
                    .*/error/.*
                </filter>
                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude" caseSensitive="false">
                    .*/page/calrss/.*
                </filter>
                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude" caseSensitive="false">
                    .*/page/rss/.*
                </filter>
                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude" caseSensitive="false">
                    .*/
                </filter>
                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude" caseSensitive="false">
                    .*/LightBox.aspx
                </filter>
                <filter class="com.norconex.importer.handler.filter.impl.NumericMetadataFilter" onMatch="exclude" field="docSize">
                    <condition operator="lt" number="1048575"/>
                </filter>
                <filter class="com.norconex.importer.handler.filter.impl.EmptyMetadataFilter" onMatch="exclude" fields="id" />
            </referenceFilters>

            <committer class="com.norconex.committer.cloudsearch.CloudSearchCommitter">
                <fixBadIds>true</fixBadIds>
                <documentEndpoint>...</documentEndpoint>
                <accessKey>...</accessKey>
                <secretKey>...</secretKey>
                <maxRetries>2</maxRetries>
                <maxRetryWait>30000</maxRetryWait>
                <commitBatchSize>10</commitBatchSize>
                <sourceReferenceField keep="true">id</sourceReferenceField>
            </committer>

        </crawler>
    </crawlers>

</httpcollector>
`

**Comment by essiembre** [comment] 2017-11-22 02:36
About the excel exception, I wonder if it is an issue related to https://github.com/Norconex/importer/issues/67, which can be resolved by adding this to your document fetcher:
```xml
<documentFetcher detectContentType="true" detectCharset="true" ...
```
If it does not do it, can you share a faulty Excel document so I can reproduce?

About the "Document too large", this is a limitation of CloudSearch.  The document size limit is 1MB (as described here: http://docs.aws.amazon.com/cloudsearch/latest/developerguide/limits.html).  You have a few options there.  You can reject large documents by combining ``DocumentLengthTagger`` with ``NumericMetadataFilter`` as post-parse handlers.

You can also truncate the long content with ``SubstringTransformer``, like this (replace the "end" value to what you want):
```xml
<transformer class="com.norconex.importer.handler.transformer.impl.SubstringTransformer" end="10000"/>
```
Finally, you can also create your own ``IDocumentSplitter`` to break large documents into smaller ones based on a given max length.  We can also make this a feature request if you want.

About the ID being empty, unless you know for sure you are getting an "id" field somehow from parsing documents, remove the ``<sourceReferenceField>``.   Can you share a document causing this?

**Comment by jerrywithaz** [comment] 2017-11-22 17:17
Thanks, essiembre.

We've just decided to ignore XLS files because they're an old format and not worth the trouble.

The SubstringTransformer was just what I was looking for! Although, one thing is confusing to me. When I look at the docSize for some of my PDFS they seem to be larger than the 1MB limit that Amazon imposes. For example I have a pdf with a docSize (From the DocumentLengthTagger) of 2689443 bytes (I assume that's in bytes) which would make that document 2.68 megabytes. So, I am a little confused on what limit to set the NumericMetadataFilter on. 

Do you know any advice regarding this? Does the DocumentLengthTagger represent the size of the file or the size of the document that is sent to Amazon?

**Comment by jerrywithaz** [comment] 2017-11-22 18:36
Never mind, I answered my own question! Thanks so much for your help with this product so far everything works great!

**Comment by essiembre** [comment] 2017-11-22 23:32
I know you've found your answer, but in case others may be wondering...

It depends on where you get document length.   As the last step of the Import process is what you want to do since it will be the actual size sent to your Committer at that point (usually much smaller than the original file size).

In terms of the difference in byte size vs character size, it depends on the character set and actual characters used in your document. After the document has been imported, it should be UTF-8.  If the characters are all in the ASCII range, you can usually assume the number of bytes is the number of character.  If you have non-ASCII characters, then those characters can take more bytes.

I would not mind fixing your XLS issue so if you change your mind on that one, please re-open this ticket (or create another one).

**Closed by essiembre** 2017-11-22 23:32 UTC
