### ISSUE TITLE
where fetched documents saved?

### ISSUE THREAD

**Issue by doaa-khaled** [Norconex/collector-http#259] opened 2016-06-16 11:18 UTC
I set in configuration xml file the option of fetching documents by that 
<documentFetcher class="com.norconex.collector.http.fetch.impl.GenericDocumentFetcher">
      <validStatusCodes>200</validStatusCodes>
      <notFoundStatusCodes>404</notFoundStatusCodes>
      <headersPrefix>fetched_doc_header</headersPrefix>
</documentFetcher>
but I didn't get any files downloads?? what is wrong here ?

**Comment by liar666** [comment] 2016-06-16 13:50
See my answer to https://github.com/Norconex/collector-http/issues/257

**Comment by essiembre** [comment] 2016-06-16 15:14
Closing since duplicate of #257.

**Closed by essiembre** 2016-06-16 15:14 UTC
Labels: duplicate
