### ISSUE TITLE
How to encrypt credentials within the configuration file

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#178] opened 2015-11-03 17:30 UTC
hi team!
as far as I can see, all credentials (e.g. authPassword) should be put as clear text into the configuration file.
Would it be possible to add an encryption feature? E.g. with an external "key" file.

Thank you!

**Comment by essiembre** [comment] 2015-11-05 04:23
Yes, there is currently no way to encrypt them.  You would have to restrict access to the config file if that's a concern to you.  Normally when crawling protected sites, you would use a "system" account if you can and not a personal account.  Regardless, I can see the need.  We can make this a feature request, but how exactly do you suggest this?  

Would you have an extra configurable option that would be the path to the key file?  Anyone would know where to grab that file from the config.  With the encrypted password and the key, you have a security concern there too.  It's different than using a key to SSH somewhere.  In our case the app has to decrypt before sending the password over as plain text to, for instance, the HTTP Basic auth request. Given this is open-source, they can use same code to de-crypt with your key and get the password.

We can add something that would prevent "casual snooping", but beyond that I am not too sure what would work best.  Ideas?

**Comment by jetnet** [comment] 2015-11-09 12:50
Hi Pascal,

an external key-file is required for production environments - the segregation of duties principle.
The dev team would build a production package with the encrypted credentials, which they would get from the ops guys having the key file.

Thanks!

**Comment by essiembre** [comment] 2015-11-09 15:35
I understand the principle, I am just not convinced how this could be made fully secure, given the HTTP Collector is already pre-packaged and source code is known.  I am marking this as a feature request and we'll investigate.

**Comment by jetnet** [comment] 2015-11-09 17:48
it will never be fully secure, of course :)
but some companies do not allow keeping credentials as clear text in configuration files :)
Thank you for the feature request!

**Comment by essiembre** [comment] 2015-11-14 04:56
You can now encrypt password in [2.4.0-SNAPSHOT](https://www.norconex.com/collectors/collector-http/download). An [FAQ entry](https://www.norconex.com/collectors/collector-http/faq#toc3) has been added explaining how to use it.

**Comment by essiembre** [comment] 2015-12-05 02:45
@jetnet, have you had a chance to test the new password-encryption feature?

**Comment by jetnet** [comment] 2015-12-18 10:21
hi Pascal, I apologize for keeping you waiting (was concentrated on the installation of the backend).
Now it's the connector's turn :)
I'm very impressed by the support of an open source product!
The password encryption with an external key - that is exactly what an enterprise infrastructure requires.
I'll give it a try asap and will let you know.
Thanks again!

**Comment by jetnet** [comment] 2015-12-28 19:47
So, I'm very impressed by the Encryption mechanism you have implemented - it provides a lot of options: test, file, env, properties - very useful!
The beta-testing phase begins now :)

`java version "1.7.0_80"`

key-file encryption does not work:
```
$ cat /tmp/key
tZxM695bO+w=
$ java -cp norconex-commons-lang-1.9.0-20151211.050124-7.jar com.norconex.commons.lang.encrypt.EncryptionUtil encrypt -f /tmp/key passw0rd
Exception in thread "main" com.norconex.commons.lang.encrypt.EncryptionException: Encryption failed.
	at com.norconex.commons.lang.encrypt.EncryptionUtil.encrypt(EncryptionUtil.java:164)
	at com.norconex.commons.lang.encrypt.EncryptionUtil.main(EncryptionUtil.java:84)
Caused by: java.security.spec.InvalidKeySpecException: Password is not ASCII
	at com.sun.crypto.provider.PBEKey.<init>(PBEKey.java:63)
	at com.sun.crypto.provider.PBEKeyFactory.engineGenerateSecret(PBEKeyFactory.java:116)
	at javax.crypto.SecretKeyFactory.generateSecret(SecretKeyFactory.java:335)
	at com.norconex.commons.lang.encrypt.EncryptionUtil.encrypt(EncryptionUtil.java:149)
	... 1 more
```

env key does not work:
```
$ k="tZxM695bO+w="
$ java -cp norconex-commons-lang-1.9.0-20151211.050124-7.jar com.norconex.commons.lang.encrypt.EncryptionUtil encrypt -e k passw0rd
passw0rd
```

**Comment by essiembre** [comment] 2015-12-28 19:58
Thanks for the good words!  For the env key issue, do you get the same error as for the key-file?  It seems to be related to charset ("Password is not ASCII").   What is your shell/OS charset?  I will investigate but in the mean time, as a workaround, can you see if it works when you pass the password as ASCII?

**Comment by jetnet** [comment] 2015-12-28 20:46
I thought, the password and the key in my tests were ASCII chars...
I tested with `LC_ALL=C` on Ubuntu

**Comment by essiembre** [comment] 2015-12-28 21:02
Just so I test with the same, can you paste the output of the ``locale`` command?

**Comment by essiembre** [comment] 2015-12-29 03:54
I was able to reproduce on Linux and it was not a direct problem with the charset.  On Linux, pressing enter to submit your command will send a new line character with the last argument. It very often is a non-issue, but in this case that is causing the error.  Simply stripping the newline character solved it.  I produced a new [snapshot release](https://www.norconex.com/collectors/collector-http/download) with the fix. Please give it another try and let me know.

**Comment by jetnet** [comment] 2016-01-06 21:11
The key-file works now - thank you!
the "-e" option still needs to be fixed:
```
$ k=MasterPassw0rd
$ java -cp norconex-http-collector/lib/norconex-commons-lang-1.9.0-20151229.033150-8.jar com.norconex.commons.lang.encrypt.EncryptionUtil encrypt -e k "encrypt me"
encrypt me
```

A question to some other issue - I have the same (or a similar) problem as described in [issue #202](https://github.com/Norconex/collector-http/issues/202), but the most latest snapshot does not solve the problem. Can we re-open this issue, or should I open a new one? 
Thank you!

**Comment by essiembre** [comment] 2016-01-06 21:20
Thanks!

Since #202 is pretty long already and the original issue i that one has been resolved, Please open a new one, and make sure to attach your config and/or enough info to reproduce.

**Closed** 2016-01-06 21:21 UTC
Labels: feature-request, fixed/done
