### ISSUE TITLE
canonicalLinkDetector rejects pages when <link rel="canonical"> points to current reference

### ISSUE THREAD

**Issue by ronjakoi** [Norconex/collector-http#646] opened 2019-10-11 11:31 UTC
Our website contains pages with `<link rel="canonical" href="foo">`, where "foo" is the url of the page itself. HTTP Collector 2.8.0 seems to reject these pages erroneously.

I made this minimal config:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="test">
    <progressDir>/home/ronja/canonical-test/progress</progressDir>
    <logsDir>/home/ronja/canonical-test/logs</logsDir>
    <workDir>/home/ronja/canonical-test/work</workDir>
    <crawlers>
        <crawler id="test-canonical">
            <startURLs stayOnDomain="true">
                <url>https://www.helsinki.fi/en/helsinki-centre-for-digital-humanities</url>
            </startURLs>
            <maxDepth>1</maxDepth>
            <canonicalLinkDetector class="com.norconex.collector.http.url.impl.GenericCanonicalLinkDetector" ignore="false"/>
            <committer class="com.norconex.committer.core.impl.JSONFileCommitter">
                <directory>/home/ronja/canonical-test/json</directory>
                <pretty>true</pretty>
            </committer>
        </crawler>
    </crawlers>
</httpcollector>
```

This is the log when I run the collector:

```
[non-job]: 2019-10-11 14:11:54 INFO - Starting execution.
[non-job]: 2019-10-11 14:11:54 INFO - Version: Norconex HTTP Collector 2.8.0 (Norconex Inc.)
[non-job]: 2019-10-11 14:11:54 INFO - Version: Norconex Collector Core 1.9.0 (Norconex Inc.)
[non-job]: 2019-10-11 14:11:54 INFO - Version: Norconex Importer 2.8.0 (Norconex Inc.)
[non-job]: 2019-10-11 14:11:54 INFO - Version: Norconex JEF 4.1.0 (Norconex Inc.)
[non-job]: 2019-10-11 14:11:54 INFO - Version: Norconex Committer Core 2.1.2 (Norconex Inc.)
test-canonical: 2019-10-11 14:11:54 INFO - Running test-canonical: BEGIN (Fri Oct 11 14:11:54 EEST 2019)
test-canonical: 2019-10-11 14:11:54 INFO - test-canonical: RobotsTxt support: true
test-canonical: 2019-10-11 14:11:54 INFO - test-canonical: RobotsMeta support: true
test-canonical: 2019-10-11 14:11:54 INFO - test-canonical: Sitemap support: true
test-canonical: 2019-10-11 14:11:54 INFO - test-canonical: Canonical links support: true
test-canonical: 2019-10-11 14:11:54 INFO - test-canonical: User-Agent: <None specified>
test-canonical: 2019-10-11 14:11:54 INFO - test-canonical: Initializing sitemap store...
test-canonical: 2019-10-11 14:11:54 INFO - test-canonical: Done initializing sitemap store.
test-canonical: 2019-10-11 14:11:55 ERROR - Could not obtain sitemap: https://www.helsinki.fi/sitemap_index.xml.  Expected status code 200, but got 301
test-canonical: 2019-10-11 14:11:55 ERROR - Could not obtain sitemap: https://www.helsinki.fi/sitemap.xml.  Expected status code 200, but got 301
test-canonical: 2019-10-11 14:11:55 INFO - 1 start URLs identified.
test-canonical: 2019-10-11 14:11:55 INFO -           CRAWLER_STARTED
test-canonical: 2019-10-11 14:11:55 INFO - test-canonical: Crawling references...
test-canonical: 2019-10-11 14:11:57 INFO -          DOCUMENT_FETCHED: https://www.helsinki.fi/en/helsinki-centre-for-digital-humanities
test-canonical: 2019-10-11 14:11:57 INFO -     REJECTED_NONCANONICAL: https://www.helsinki.fi/en/helsinki-centre-for-digital-humanities
test-canonical: 2019-10-11 14:11:58 INFO -          DOCUMENT_FETCHED: https://www.helsinki.fi/sites/all/themes/helsingin_yliopisto/images/hy_logo_black.png
test-canonical: 2019-10-11 14:11:58 INFO -       CREATED_ROBOTS_META: https://www.helsinki.fi/sites/all/themes/helsingin_yliopisto/images/hy_logo_black.png
test-canonical: 2019-10-11 14:11:58 INFO -            URLS_EXTRACTED: https://www.helsinki.fi/sites/all/themes/helsingin_yliopisto/images/hy_logo_black.png
test-canonical: 2019-10-11 14:11:58 INFO -         DOCUMENT_IMPORTED: https://www.helsinki.fi/sites/all/themes/helsingin_yliopisto/images/hy_logo_black.png
test-canonical: 2019-10-11 14:11:58 INFO - JSON File created: /home/ronja/canonical-test/json/2019-10-11T02-11-58-169_1.json
test-canonical: 2019-10-11 14:11:58 INFO -    DOCUMENT_COMMITTED_ADD: https://www.helsinki.fi/sites/all/themes/helsingin_yliopisto/images/hy_logo_black.png
test-canonical: 2019-10-11 14:11:58 INFO - test-canonical: Reprocessing any cached/orphan references...
test-canonical: 2019-10-11 14:11:58 INFO - test-canonical: Crawler finishing: committing documents.
test-canonical: 2019-10-11 14:11:58 INFO - test-canonical: 2 reference(s) processed.
test-canonical: 2019-10-11 14:11:58 INFO -          CRAWLER_FINISHED
test-canonical: 2019-10-11 14:11:58 INFO - test-canonical: Crawler completed.
test-canonical: 2019-10-11 14:11:58 INFO - test-canonical: Crawler executed in 3 seconds.
test-canonical: 2019-10-11 14:11:58 INFO - test-canonical: Closing sitemap store...
test-canonical: 2019-10-11 14:11:58 INFO - Running test-canonical: END (Fri Oct 11 14:11:54 EEST 2019)
```

The resulting JSON does not contain the HTML page, just metadata on the image:

```json
[
  {
  "doc-add": {
    "reference": "https://www.helsinki.fi/sites/all/themes/helsingin_yliopisto/images/hy_logo_black.png",
    "metadata": "ObservableMap [map=ObservableMap [map=ObservableMap [map={collector.content-type=[image/png], document.contentFamily=[image], Transparency Alpha=[nonpremultipled], tiff:ImageLength=[650], Compression CompressionTypeName=[deflate], Data BitsPerSample=[8 8 8 8], Last-Modified=[Tue, 28 Jun 2016 07:07:31 GMT], Data PlanarConfiguration=[PixelInterleaved], document.reference=[https://www.helsinki.fi/sites/all/themes/helsingin_yliopisto/images/hy_logo_black.png], IHDR=[width=650, height=650, bitDepth=8, colorType=RGBAlpha, compressionMethod=deflate, filterMethod=adaptive, interlaceMethod=none], X-Frame-Options=[sameorigin], X-Varnish=[44999841 10243343], collector.is-crawl-new=[true], Chroma ColorSpaceType=[RGB], X-Varnish-Server=[cubert-4.it.helsinki.fi], collector.depth=[0], Content-Length=[14334], tiff:BitsPerSample=[8 8 8 8], X-Backend=[flexo], Age=[774876], Content-Type=[image/png], height=[650], X-Parsed-By=[org.apache.tika.parser.DefaultParser, org.apache.tika.parser.image.ImageParser], Text TextEntry=[keyword=Software, value=Adobe ImageReady, encoding=ISO-8859-1, compression=none, keyword=Software, value=Adobe ImageReady], Connection=[keep-alive], Dimension PixelAspectRatio=[1.0], X-Varnish-Cache-Hits=[1741], Date=[Wed, 02 Oct 2019 11:57:21 GMT], Via=[1.1 varnish-v4], Accept-Ranges=[bytes], X-Varnish-Cacheable=[YES], collector.referrer-reference=[https://www.helsinki.fi/en/helsinki-centre-for-digital-humanities], Cache-Control=[max-age=1209600], Compression NumProgressiveScans=[1], ETag=[\"37fe-536514a61c742\"], document.contentType=[image/png], Chroma BlackIsZero=[true], Compression Lossless=[true], width=[650], Dimension ImageOrientation=[Normal], Expires=[Wed, 16 Oct 2019 11:57:21 GMT], X-Varnish-Cache=[HIT], tiff:ImageWidth=[650], Chroma NumChannels=[4], Data SampleFormat=[UnsignedIntegral]}]]]",
    "content": ""
  }
}
```

Nothing in the canonicalLinkDetector [documentation](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericCanonicalLinkDetector.html) or [Google's guidelines](https://support.google.com/webmasters/answer/139066) seems to suggest that pages should avoid pointing to themselves with `<link rel="canonical">` like our site does:

`<link rel="canonical" href="https://www.helsinki.fi/en/helsinki-centre-for-digital-humanities">`

**Comment by essiembre** [comment] 2019-10-15 05:25
You are correct to assume that self-referencing canonical URLs should be handled just fine.  

You can try upgrading since there have been a few changes to canonical URL handling in the most recent versions (including snapshot), but I am not convinced they will address your issue. 

I could not reproduce your test to investigate. I get ``Error 503 Backend fetch failed`` when trying to access the URL from your example.  Any chance you can bring that page back to normal?

**Comment by ronjakoi** [comment] 2019-10-15 05:35
> I could not reproduce your test to investigate. I get Error 503 Backend fetch failed when trying to access the URL from your example. Any chance you can bring that page back to normal?

I tried it just now and it works for me. Probably a temporary cache glitch.

**Comment by ronjakoi** [comment] 2019-10-15 05:38
I also just tried the same config with 2.8.1. Same problem:

```
INFO  [CrawlerEventManager]          DOCUMENT_FETCHED: https://www.helsinki.fi/en/helsinki-centre-for-digital-humanities
INFO  [CrawlerEventManager]     REJECTED_NONCANONICAL: https://www.helsinki.fi/en/helsinki-centre-for-digital-humanities
```

**Comment by essiembre** [comment] 2019-10-28 01:48
I found the issue. The HTTP response header for the page also has a non-canonical directive:
```
link: <https://www.helsinki.fi/sites/all/themes/helsingin_yliopisto/images/hy_logo_black.png>; rel="image_src",<https://www.helsinki.fi/en/helsinki-centre-for-digital-humanities>; rel="canonical",<https://www.helsinki.fi/en/node/38547>; rel="shortlink",<https://www.helsinki.fi/en/helsinki-centre-for-digital-humanities>; rel="hreflang_en"
```
The crawler right now is assuming only one value was possible for ``Link:`` in the HTTP headers and as such grabbed the first one, which points to an image URL (which is canonically different).  After reading I can tell it is a wrong assumption and the HTTP header should be better parsed (https://tools.ietf.org/html/rfc5988#section-5.3).  

Will fix.

**Comment by essiembre** [comment] 2019-10-28 03:02
The latest HTTP Collector snapshot now has a fix for this.  Please confirm.

**Comment by ronjakoi** [comment] 2019-10-28 11:24
Confirmed working in latest snapshot:

`INFO  [CrawlerEventManager]    DOCUMENT_COMMITTED_ADD: https://www.helsinki.fi/en/helsinki-centre-for-digital-humanities`

Thank you for the fix. Is there an ETA on 2.9.0 stable?

**Comment by essiembre** [comment] 2019-12-22 07:17
2.9.0 released.

**Closed by essiembre** 2019-12-22 07:17 UTC
Labels: bug, fixed/done
