### ISSUE TITLE
"id" must be less than 128 characters

### ISSUE THREAD

**Issue by krishnateja-ravipati** [Norconex/collector-http#412] opened 2017-10-19 15:55 UTC
Hello Essiembre,

I am currently facing the below-mentioned issue while committing documents to CloudSearch,
**CloudSearch error: { [""id" must be less than 128 characters**

According to HTTP collector configuration, URL of a page is stored as "id" for each document, which is the default implementation. What should be the configuration change so that uuid can be stored as the id of the document and URL stored in an index field in **CloudSearch**?

Thanks,
Krishna Teja

**Comment by essiembre** [comment] 2017-10-20 03:53
This looks like a duplicate of #323 and #382.  Please have a look for possible solutions and confirm.

**Comment by krishnateja-ravipati** [comment] 2017-10-20 07:58
Hello Essiembre,

In solution #323, changes the URL to be crawled. All hyphens(-) in URL are replaced with an underscore(_) for which crawler returns errors of incorrect URL.

In solution #382, replacements suggested in URLNormalizer returns only 310 documents for committing as compared to 510 documents I was able to parse for committing originally.

Instead, can you suggest any other alternative configuration to solve this id length issue? 
Is it possible to put a constant key value as id so that I do not face updating issues when I recrawl again?
How can I store URL as index field instead of document id?

Thanks
Krishna Teja

**Comment by krishnateja-ravipati** [comment] 2017-10-21 10:41
Hello Essiembre,

I am now able to used ID generated by UUID Tagger as document ID and also store the document.reference as URL in the index field of Cloudsearch.

Can you throw more light about whether updating process works when I recrawl using UUID as document ID?

**Comment by essiembre** [comment] 2017-10-22 06:05
Since UUIDs will be different each time, using them as IDs is not the best option for updates.  

A new [snapshot version](https://www.norconex.com/collectors/committer-cloudsearch/download) of the [CloudSearch Committer](https://www.norconex.com/collectors/committer-cloudsearch/latest/apidocs/com/norconex/committer/cloudsearch/CloudSearchCommitter.html) was just released.  It has a new flag for "fixing" long ids and those having invalid characters.  Add the following to your committer config:

```xml
  <fixBadIds>true</fixBadIds>
```

Have a look at the Class documentation for more information.  

Please give it a try and confirm.

**Comment by krishnateja-ravipati** [comment] 2017-10-23 10:03
Hello Essiembre,

Thanks for new feature update. <fixBadIds>true</fixBadIds> seems to have solved the issue temporarily. Will have continuous look on the crawling behavior and will get back to you if I find any issue with this feature.

Thank you
R Krishna Teja

**Comment by essiembre** [comment] 2017-10-29 05:22
Does it still work for you?

There is no official release date, but hopefully, 2.8.0 "stable" will be out anytime between now and a month or two.

**Comment by krishnateja-ravipati** [comment] 2017-10-29 06:54
@essiembre I have a question regarding extracting content from a document.

I would like to pick up only the content available in the body of the page and exclude common headers and footers available on all pages. The body is separated from rest of the page by `<main>` HTML tags. Can you suggest which tagger would be suitable to implement my requirement?

**Comment by essiembre** [comment] 2017-10-29 16:38
Please create new tickets for new questions.  I have done so for you this time here: #418.

I am closing this one since the original issue has been resolved.  If you suspect issues with document updates on re-crawl, feel free to re-open.

**Closed by essiembre** 2017-10-29 16:38 UTC
