### ISSUE TITLE
Alternative canonical expressions

### ISSUE THREAD

**Issue by simonwibberley** [Norconex/collector-http#697] opened 2020-05-27 11:28 UTC
Some sites choose to exhibit canonical references in a non-standard way, for example https://www.glasistre.hr/ currently use:
`<meta property="canonical" href="https://www.glasistre.hr/">`

This leads to a near infinite crawl loop since their back references contain a source link.

**Comment by essiembre** [comment] 2020-06-01 21:19
Thanks for your contribution!   I am not sure what you mean by "near infinite" loop given there should be none if the canonical was not detected.  Plus, the crawler is equipped to deal with canonical URL loops.  I am closing since you committed a fix, but if you found a way to produce an infinite loop, please open a new tickets with a config to reproduce.

**Closed by essiembre** 2020-06-01 21:19 UTC
