### ISSUE TITLE
referenceFilters and robotsTxt: robots.txt being checked for "external" sites

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#168] opened 2015-10-15 09:35 UTC
Dear norconex team,

could you please clarify, why the http collector does check the robots.txt of the "remote" (or "external") sites, although it is configured to "stay-on-site", e.g.
```
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
        <url>https://www.intranet.site.com/index.htm</url>
</startURLs>
```
```
<referenceFilters>
        <filter 
            class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter"
            onMatch="exclude" >jpg,gif,png,ico,css,js</filter>
</referenceFilters>
```
```
<robotsTxt ignore="false" class="com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider"/>
```

When the collector finds an external link (link to another site/domain), it tries to download the robots.txt from that site. Basically, it not that bad for the intranet sites, but if a link is pointed to an Internet site, the crawler gets run into a connection timeout.

I tried to add an "include" regex (with the domain name) into `<referenceFilters>`, but it did not help.
The question, is it possible to disable the checking of "robots.txt" not belonging to the sites configured inside `<startURLs>`

Thanks!

**Comment by essiembre** [comment] 2015-10-17 03:44
I could not reproduce this. It never tries to download the ``robots.txt`` on another site. Did you encounter this with 2.3.0-SNAPSHOT? Can you please attached your config? 

If you change the loglevel in ``classes/log4j.properties`` to DEBUG, you should see lines like these to indicate external URLs are rejected.  Do you get them?
```
DEBUG [LinkExtractorStage] URL not in crawl scope: http://externalsite.com/blah
DEBUG [URLCrawlScopeStrategy] Rejected domain for: http://externalsite.com/blah
```

**Comment by jetnet** [comment] 2015-10-19 13:13
Just tested again with the latest snapshot (norconex-collector-http-2.3.0-20151017.032546-23.zip).
I cannot reproduce the issue now - no external "robots.txt" are getting fetched.

P.S. the more I work with the http-collector, the more I like it :) You guys have been doing a really good job!

**Comment by essiembre** [comment] 2015-10-19 16:37
Good feedback like this is why we keep doing it.  Thank you!

**Comment by comschmid** [comment] 2015-10-20 09:14
Sorry to drop in, but even with the latest snapshot, I experience the same issue. 
I realized this behavior when I saw sporadic exceptions in the log (e.g. SSLHandshakeException) during a crawl with the message "Not able to obtain robots.txt at: ..." for external references that should not be crawled but only listed by the crawler event "URLS_EXTRACTED". 

The setting of the `stayOnDomain` attribute doesn't change the behaviour and I also use a RegexReferenceFilter that is applied in code.

Unfortunately, I can't see the LinkExtractorStage or URLCrawlScopeStrategy in the log for the fetched robot.txt (after changing the collectors to DEBUG), but I see it in the stack trace, e.g.:

```
WARN  [StandardRobotsTxtProvider] Not able to obtain robots.txt at: https://www.openstreetmap.ch/robots.txt
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1904)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:279)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:273)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1446)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:209)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:901)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:837)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1023)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider.getRobotsTxt(StandardRobotsTxtProvider.java:80)
	at com.norconex.collector.http.pipeline.queue.HttpQueuePipelineContext.<init>(HttpQueuePipelineContext.java:41)
	at com.norconex.collector.http.pipeline.importer.LinkExtractorStage.queueURL(LinkExtractorStage.java:131)
	at com.norconex.collector.http.pipeline.importer.LinkExtractorStage.executeStage(LinkExtractorStage.java:89)
	at com.norconex.collector.http.pipeline.importer.AbstractImporterStage.execute(AbstractImporterStage.java:31)
	at com.norconex.collector.http.pipeline.importer.AbstractImporterStage.execute(AbstractImporterStage.java:24)
	at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:90)
	at com.norconex.collector.http.crawler.HttpCrawler.executeImporterPipeline(HttpCrawler.java:285)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:475)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:376)
	at com.norconex.collector.core.crawler.AbstractCrawler$ProcessReferencesRunnable.run(AbstractCrawler.java:703)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

My config is located at [#163](https://github.com/Norconex/collector-http/issues/163#issuecomment-147985321). What am I missing?
Thanks for your help!

**Comment by essiembre** [comment] 2015-10-20 19:53
Re-opening. I will try reproduce with your config.

**Comment by essiembre** [comment] 2015-10-20 19:59
@comschmid, after approximately how many docs processed do you get this exception?

**Comment by comschmid** [comment] 2015-10-21 07:33
First, let me explain that the exception is correct, since the SSL certificate is expired. Thanks to this kind of exceptions I realized that robots.txt of external references are fetched, which is not intended, according the current configuration. This exception is just an example and I just realized, that this exception is not thrown for this exact configuration, but an SSLHandshakeException for another external domain is thrown.

Now, let me answer your question:
I don't see that there is a certain limit of docs that need to be processed.
As of now, a complete crawl with this configuration produces 58 documents and I see a SSLHandshakeException after about 20% of the log output (with log level DEBUG for the collector).

I also checked with Wireshark (with filter 'http.connection') and I already see from the beginning a lot of connections to external domains, requesting the robots.txt.

**Comment by essiembre** [comment] 2015-10-22 04:34
@comschmid, I just crawl "http://www.etools.ch" with your config.  It worked just fine. I got no exception and the site mentioned in the exception your reported was filtered out and no attempt to get a robot for it was made.  The rejection:

```
Issue Crawler: 2015-10-22 00:23:13 DEBUG - Rejected domain for: https://www.openstreetmap.ch/
Issue Crawler: 2015-10-22 00:23:13 DEBUG - URL not in crawl scope: https://www.openstreetmap.ch/ 
```
Do you get that rejection too?

What may be happening is using an old crawl database.  Did  you delete your work directory before trying again (especially the crawldb)? When new features are introduced or when you make particular config changes, you sometimes need to do a fresh re-crawl. The reason being, those external sites may have been previously crawled so the crawler has kept a memory of them and tries them again in case they have changed.

Try again with a fresh crawl and let me know if you still have the problem.

**Comment by comschmid** [comment] 2015-10-22 14:52
Thanks for your feedback!

Unfortunately I don't get this rejection messages, even by setting all log levels to DEBUG.

And yes, I did a fresh crawl.

FYI: I set the RegexReferenceFilter with the value `https?://www\.etools\.ch/.*` in code.
There must be something I looked over...

**Comment by essiembre** [comment] 2015-10-22 15:44
This is not related to why it tries to go outside, but if you want to get rid of the SSL Exception, this flag will probably do it for you:
```xml
<httpClientFactory>
  <trustAllSSLCertificates>true</trustAllSSLCertificates>
</httpClientFactory>
```

Your RegexReferenceFilter suggests I did not use the exact same config as yours.  If you do it in the code, I understand it may be trouble to convert it to a config.  This has not been tried a lot, but you can try to save the config created via code to a file using ``HttpCrawlerConfig#saveToXML(Writer)`` and attach it here.

**Comment by comschmid** [comment] 2015-10-22 16:14
Thanks for the pointer concerning trusting all SSL certificates.

Unfortunately, the creation of the config XML stops somewhere in the middle with an NPE:
```java
Exception in thread "main" java.lang.NullPointerException
	at com.ctc.wstx.sw.BaseNsStreamWriter.doWriteAttr(BaseNsStreamWriter.java:493)
	at com.ctc.wstx.sw.BaseNsStreamWriter.writeAttribute(BaseNsStreamWriter.java:228)
	at com.norconex.commons.lang.xml.EnhancedXMLStreamWriter.writeAttribute(EnhancedXMLStreamWriter.java:208)
	at com.norconex.importer.handler.filter.impl.RegexMetadataFilter.saveFilterToXML(RegexMetadataFilter.java:138)
	at com.norconex.importer.handler.filter.AbstractDocumentFilter.saveHandlerToXML(AbstractDocumentFilter.java:134)
	at com.norconex.importer.handler.AbstractImporterHandler.saveToXML(AbstractImporterHandler.java:224)
	at com.norconex.importer.ImporterConfig.writeObject(ImporterConfig.java:295)
	at com.norconex.importer.ImporterConfig.writeObject(ImporterConfig.java:282)
	at com.norconex.importer.ImporterConfig.writeHandlers(ImporterConfig.java:275)
	at com.norconex.importer.ImporterConfig.saveToXML(ImporterConfig.java:246)
	at com.norconex.collector.core.crawler.AbstractCrawlerConfig.writeObject(AbstractCrawlerConfig.java:443)
	at com.norconex.collector.core.crawler.AbstractCrawlerConfig.writeObject(AbstractCrawlerConfig.java:423)
	at com.norconex.collector.core.crawler.AbstractCrawlerConfig.saveToXML(AbstractCrawlerConfig.java:266)
...
```

**Comment by essiembre** [comment] 2015-10-22 16:24
Yeah, saving the config that way is very rarely done.  It does not mean it should not work though :-)  I will look at fixing the issue you just reported.

**Comment by essiembre** [comment] 2015-10-25 06:35
The [latest snapshot](https://www.norconex.com/collectors/collector-http/download) should save properly now. I recommend you try again with it and attach the generated config. If you are overwriting an existing install with the snapshot, make sure you do not get Jar conflicts (different versions of the same Jars under lib).

**Comment by comschmid** [comment] 2015-10-25 11:17
Thanks again for you attention and support!

I updated the norconex jars to the latest snapshot as advised and now I could generate the corresponding XML:-) Please note, that the external robots.txt still gets fetched.

Following the resulting XML, created from `HttpCrawlerConfig` :
```xml
<crawler class="com.norconex.collector.http.crawler.HttpCrawlerConfig" id="www.etools.ch">
	<numThreads>2</numThreads>
	<workDir>D:\data\workspaces\mole\lizard\collector\work</workDir>
	<maxDocuments>-1</maxDocuments>
	<orphansStrategy>IGNORE</orphansStrategy>
	<crawlDataStoreFactory class="com.norconex.collector.core.data.store.impl.mapdb.MapDBCrawlDataStoreFactory" />
	<referenceFilters>
		<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include" caseSensitive="false">https?://www\.etools\.ch/.*</filter>
		<filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter" onMatch="exclude" caseSensitive="false">jpg,jpeg,gif,png,ico,css,js</filter>
		<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude" caseSensitive="true">.+\?.*</filter>
	</referenceFilters>
	<metadataFilters>
		<filter class="com.norconex.collector.core.filter.impl.RegexMetadataFilter" onMatch="exclude" caseSensitive="false" field="Content-Type">.*css.*|.*javascript.*</filter>
	</metadataFilters>
	<crawlerListeners>
		<listener class="com.comcepta.lizard.vadian.VadianEventListener" />
	</crawlerListeners>
	<importer>
		<tempDir>D:\data\workspaces\mole\lizard\collector\work\temp</tempDir>
		<parseErrorsSaveDir>D:\data\workspaces\mole\lizard\collector\work\parseerrors</parseErrorsSaveDir>
		<maxFileCacheSize>10485760</maxFileCacheSize>
		<maxFilePoolCacheSize>104857600</maxFilePoolCacheSize>
		<preParseHandlers>
			<tagger class="com.norconex.importer.handler.tagger.impl.DocumentLengthTagger" field="document.size.preparse" overwrite="false" />
		</preParseHandlers>
		<tagger class="com.norconex.importer.parser.GenericDocumentParserFactory" splitEmbedded="false" />
		<postParseHandlers>
			<tagger class="com.norconex.importer.handler.tagger.impl.ConstantTagger" />
			<filter class="com.norconex.importer.handler.filter.impl.RegexMetadataFilter" onMatch="exclude" caseSensitive="false">.*</filter>
			<transformer class="com.norconex.importer.handler.transformer.impl.ReduceConsecutivesTransformer" maxReadSize="65536" caseSensitive="true">
				<reduce>\s</reduce>
				<reduce>\n</reduce>
				<reduce>\r</reduce>
				<reduce>\t</reduce>
				<reduce>\n\r</reduce>
				<reduce>\r\n</reduce>
				<reduce>\s\n</reduce>
				<reduce>\s\r</reduce>
				<reduce>\s\r\n</reduce>
				<reduce>\s\n\r</reduce>
			</transformer>
			<transformer class="com.norconex.importer.handler.transformer.impl.ReplaceTransformer" maxReadSize="65536" caseSensitive="false">
				<replace>
					<fromValue>class=".*?"</fromValue>
					<toValue></toValue>
				</replace>
			</transformer>
			<transformer class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer" maxReadSize="65536" caseSensitive="false" inclusive="true">
				<stripBetween>
					<start>&lt;style.*?></start>
					<end>&lt;/style></end>
				</stripBetween>
				<stripBetween>
					<start>&lt;script.*?></start>
					<end>&lt;/script></end>
				</stripBetween>
			</transformer>
			<tagger class="com.norconex.importer.handler.tagger.impl.DocumentLengthTagger" field="document.size.postparse" overwrite="false" />
			<filter class="com.norconex.importer.handler.filter.impl.NumericMetadataFilter" onMatch="exclude" field="document.size.postparse">
				<condition operator="lt" number="100.0" />
			</filter>
			<tagger class="com.norconex.importer.handler.tagger.impl.LanguageTagger" shortText="false" keepProbabilities="false" fallbackLanguage="" />
			<tagger class="com.norconex.importer.handler.tagger.impl.CharacterCaseTagger">
				<characterCase fieldName="keywords" type="lower" applyTo="field" />
				<characterCase fieldName="description" type="lower" applyTo="field" />
			</tagger>
			<tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
				<fields>content,title,keywords,description,tags,collector.referrer-reference,collector.depth,document.reference,document.language,document.size.preparse,document.size.postparse</fields>
			</tagger>
		</postParseHandlers>
	</importer>
	<committer class="com.norconex.committer.solr.SolrCommitter">
		<sourceReferenceField keep="false">document.reference</sourceReferenceField>
		<targetReferenceField>id</targetReferenceField>
		<targetContentField>content</targetContentField>
		<queueDir>D:\data\workspaces\mole\lizard\collector\work\commitqueue</queueDir>
		<queueSize>10</queueSize>
		<commitBatchSize>5</commitBatchSize>
		<maxRetries>1</maxRetries>
		<maxRetryWait>5000</maxRetryWait>
		<solrURL>http://localhost:8983/solr/test1</solrURL>
		<solrUpdateURLParams>
			<commitDisabled>false</commitDisabled>
		</solrUpdateURLParams>
	</committer>
	<documentChecksummer class="com.norconex.collector.core.checksum.impl.MD5DocumentChecksummer" keep="false" targetField="collector.checksum-doc" disabled="false">
		<sourceFields>content,title,keywords,description</sourceFields>
	</documentChecksummer>
	<spoiledStateStrategyResolver class="com.norconex.collector.core.spoil.impl.GenericSpoiledReferenceStrategizer" fallbackStrategy="DELETE">
		<mapping state="BAD_STATUS" strategy="GRACE_ONCE" />
		<mapping state="NOT_FOUND" strategy="DELETE" />
		<mapping state="ERROR" strategy="GRACE_ONCE" />
	</spoiledStateStrategyResolver>
	<userAgent>Mozilla/5.0 (compatible; TestCrawler/0.1; +http://www.comcepta.com)</userAgent>
	<maxDepth>5</maxDepth>
	<keepDownloads>false</keepDownloads>
	<startURLs stayOnProtocol="false" stayOnDomain="false" stayOnPort="false">
		<url>http://www.etools.ch/</url>
	</startURLs>
	<urlNormalizer class="com.norconex.collector.http.url.impl.GenericURLNormalizer" disabled="false">
		<normalizations>lowerCaseSchemeHost,upperCaseEscapeSequence,decodeUnreservedCharacters,removeDefaultPort,removeFragment,removeDotSegments,addTrailingSlash,removeDuplicateSlashes,removeSessionIds,upperCaseEscapeSequence</normalizations>
		<replacements>
			<replace>
				<match>&amp;view=print</match>
				<replacement>&amp;view=html</replacement>
			</replace>
		</replacements>
	</urlNormalizer>
	<delay class="com.norconex.collector.http.delay.impl.GenericDelayResolver" default="1000" scope="site" ignoreRobotsCrawlDelay="false" />
	<httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
		<cookiesDisabled>false</cookiesDisabled>
		<authPort>-1</authPort>
		<authFormCharset>UTF-8</authFormCharset>
		<proxyPort>0</proxyPort>
	</httpClientFactory>
	<connectionTimeout>30000</connectionTimeout>
	<socketTimeout>30000</socketTimeout>
	<connectionRequestTimeout>30000</connectionRequestTimeout>
	<expectContinueEnabled>false</expectContinueEnabled>
	<maxRedirects>50</maxRedirects>
	<maxConnections>200</maxConnections>
	<trustAllSSLCertificates>false</trustAllSSLCertificates>
	<maxConnectionsPerRoute>20</maxConnectionsPerRoute>
	<maxConnectionIdleTime>10000</maxConnectionIdleTime>
	<maxConnectionInactiveTime>0</maxConnectionInactiveTime>
	<robotsTxt class="com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider" />
	<sitemapResolverFactory class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory" lenient="false" />
	<canonicalLinkDetector class="com.norconex.collector.http.url.impl.GenericCanonicalLinkDetector">
		<contentTypes>text/html,application/xhtml+xml,vnd.wap.xhtml+xml,x-asp</contentTypes>
	</canonicalLinkDetector>
	<metadataFetcher class="com.norconex.collector.http.fetch.impl.GenericMetadataFetcher">
		<validStatusCodes>200</validStatusCodes>
	</metadataFetcher>
	<metadataChecksummer class="com.norconex.collector.http.checksum.impl.LastModifiedMetadataChecksummer" keep="false" targetField="collector.checksum-metadata" disabled="false" />
	<httpDocumentFetcher class="com.norconex.collector.http.fetch.impl.GenericDocumentFetcher">
		<validStatusCodes>200</validStatusCodes>
		<notFoundStatusCodes>404</notFoundStatusCodes>
		<headersPrefix />
	</httpDocumentFetcher>
	<robotsMeta class="com.norconex.collector.http.robot.impl.StandardRobotsMetaProvider" />
	<linkExtractors>
		<extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor" maxURLLength="2048" ignoreNofollow="false" keepReferrerData="true">
			<contentTypes>text/html,application/xhtml+xml,vnd.wap.xhtml+xml,x-asp</contentTypes>
			<tags>
				<tag name="a" attribute="href" />
				<tag name="input" attribute="src" />
				<tag name="img" attribute="src" />
				<tag name="form" attribute="action" />
				<tag name="meta" attribute="http-equiv" />
				<tag name="link" attribute="href" />
				<tag name="iframe" attribute="src" />
				<tag name="frame" attribute="src" />
				<tag name="base" attribute="href" />
			</tags>
		</extractor>
	</linkExtractors>
	<preImportProcessors>
		<processor class="com.comcepta.lizard.vadian.VadianEventListener" />
	</preImportProcessors>
</crawler>
```

**Comment by essiembre** [comment] 2015-10-27 06:14
Thanks to your config, I was able to reproduce.  Stay tuned for a fix.

**Comment by essiembre** [comment] 2015-10-27 06:51
Fixed. Let me know how [this new snapshot release](https://www.norconex.com/collectors/collector-http/download) goes.

**Comment by comschmid** [comment] 2015-10-27 10:33
Thanks a lot, this snapshot fixed this issue, I also checked it with Wireshark and looks good!

Just a quick question: where can I add additional HTTP request headers, such as 'Accept-Language'?

BTW: when I was looking at the generated XML above, I realized that some of the child-elements of `<httpClientFactory>`appear after this element, like `<connectionTimeout>`.

**Comment by essiembre** [comment] 2015-10-28 03:01
Try to create new issues when you have questions/new issues not related to the original issue you are in. That's much easier to keep track.

Right now there is no configurable feature to add request headers.  The easiest would probably be to extend GenericHttpClientFactory to add this, by overwriting its ``buildCustomHttpClient`` method.  That's a pretty easy addition so I will add a new feature request for it. 

For the order problem when you save, that should be considered a bug so it should be in its own ticket.  I will create it this time.

Since the original issue is fixed, I am closing.

**Closed by essiembre** 2015-10-28 03:01 UTC
Labels: bug, fixed/done
