### ISSUE TITLE
WebDriverHttpFetcher with Selenium breaks include Filters

### ISSUE THREAD

**Issue by mv-ntl** [Norconex/collector-http#859] opened 2023-12-15 14:16 UTC
Hi. I'm using these versions of the Norconex Software:

```
Collector:          Norconex HTTP Collector 3.0.2 (Norconex Inc.)
Collector Core:     Norconex Collector Core 2.0.2 (Norconex Inc.)
Importer:           Norconex Importer 3.0.1 (Norconex Inc.)
Lang:               Norconex Commons Lang 2.0.2 (Norconex Inc.)
Committer(s):
  Core:             Norconex Committer Core 3.0.0 (Norconex Inc.)
  Elasticsearch:    Norconex Committer Elasticsearch 5.0.0 (Norconex Inc.)
Runtime:
  Name:             Java(TM) SE Runtime Environment
  Version:          11.0.3+12-LTS
  Vendor:           Oracle Corporation
```

I have an issue getting the following configuration to work. Unfortunately, I cannot share the actual domain, so I replaced it with `example.com`.
 

```xml
<crawler id="example.com">
    <startURLs stayOnDomain="true" stayOnPort="false" stayOnProtocol="false"
        includeSubdomains="false">
        <url>http://example.com</url>
    </startURLs>
    #set($domain    = "example.com")
    #set($domain_xn = "example.com")
    <maxDocuments>30000</maxDocuments>
	<robotsTxt ignore="false" />
	<robotsMeta ignore="false" />
	<sitemapResolver ignore="true" />

	<recrawlableResolver
        class="com.norconex.collector.http.recrawl.impl.GenericRecrawlableResolver"
        sitemapSupport="never">
        <minFrequency applyTo="reference" value="3d">.*</minFrequency>
    </recrawlableResolver>

    <!-- "referenceFilters" section with include rules are crawler's specific and defined here.
	The following placeholder will be replaced by the <referenceFilters>
	with the include rules. At least one include must match, otherwise the url will be ignored.
	All exclude rules are defined globally in "crawler-defaults"
	and you cannot just define another excludes here, as the local ones
	will replace the global ones. -->
	<referenceFilters>
        #parse("$crawlerexcluderules")
        <filter class="$filterRegexRef" onMatch="include">
            <valueMatcher method="regex">.*[\.\/]example.com.*</valueMatcher>
        </filter>
    </referenceFilters>

	<importer>
        <preParseHandlers>
            #parse("../shared/preParseHandlers.xml")
        </preParseHandlers>
        <documentParserFactory>
            #parse("../shared/documentParserFactory.xml")
        </documentParserFactory>
        <postParseHandlers>
            #parse("../shared/postParseHandlers.xml")
        </postParseHandlers>
    </importer>

    #parse("../shared/commiter-configs.xml")
    
    <httpFetchers>
        <fetcher class="com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher">
            <browser>chrome</browser>
            <remoteURL>http://localhost:44445/wd/hub</remoteURL>
            <screenshot>
                <targetDir>/tmp/crawler-screenshots</targetDir>
            </screenshot>
        </fetcher>
    </httpFetchers>
</crawler>
```

This config produces no commits at the end of the crawl. Each individual site visted results in a log statement like
```
INFO  REJECTED_FILTER - https://example.com/ - No "include" metadata filters matched.
```

Notably, this configuration works fine without the `<httpFetchers>` block and produces the desired output. I was able to verify that the docker container running selenium at `http://localhost:44445` is reachable and works.
The Crawler also produces screenshots under `/tmp/crawler-screenshots` without a problem, and these screenshots definitely show the expected text content of the crawled website.
I've tried using firefox-based Selenium instead of chrome, same result.

I've tried using a simpler expression like `.*` in `<valueMatcher method="regex">.*[\.\/]example.com.*</valueMatcher>`, but that didn't help either.

Again, I want to point out that the same configuration works as long as it's not using the WebDriverHttpFetcher.

Is the fetcher misconfigured, or is there a bug in the crawler?

**Comment by ohtwadi** [comment] 2023-12-26 16:39
Hi. 

Without a reproducible test case, this would be tough to debug. Do you see any errors? 
Could you try running selenium outside of Docker?

**Comment by mv-ntl** [comment] 2024-01-25 13:43
Hello, we tried to use a non-docker installation.
We've checked that the selenium instances work in several ways:

- Output of `curl localhost:44445/wd/hub/status` doesn't show any problems
- Can connect to the selenium instance using other libraries (e.g. I was able to connect to it using a tiny python script)
- Norconex is still able to generate screenshots of visited pages

The initial problem persits, the crawler still claims that no include filters matched.

Unfortunately I'm still unable to share the domain name or full configuration files. I understand this makes it difficult to pinpoint the issue.

**Comment by gitter355** [comment] 2024-02-13 12:03
Hello @ohtwadi , 

I'm facing same issue here where `metadataFilters` configuration seem to be ignored when using `WebDriverHttpFetcher` with the Firefox browser. The crawler rejects URLs that should be included according to my `metadataFilters` setup.

**Environment**

- Collector:  Norconex HTTP Collector 3.0.2 (Norconex Inc.)
- Collector Core:  Norconex Collector Core 2.0.2 (Norconex Inc.)
- Importer:  Norconex Importer 3.0.1 (Norconex Inc.)
- Lang:  Norconex Commons Lang 2.0.2 (Norconex Inc.)
- Committer Core: Norconex Committer Core 3.0.0 (Norconex Inc.)
- Committer Elasticsearch:  Norconex Committer Elasticsearch 5.0.0 (Norconex Inc.)
- Firefox version: 4.17.0-20240123

**Configuration**
Here is my crawler configuration that uses `WebDriverHttpFetcher`, I've used google.com website as an example:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<httpcollector id="www.google.com">
	#parse("../shared/norconex-classes.xml")
	#parse("/shared/general-configs.xml")
	<workDir>$workdir</workDir>
	<crawlers>
		<crawler id="www.google.com">
			<startURLs stayOnDomain="true" stayOnPort="false" stayOnProtocol="false" includeSubdomains="false">
				<url>https://www.google.com/</url>
			</startURLs>
			#set($domain = "www.google.com")
			#set($domain_xn = "www.google.com")
			<maxDocuments>10000</maxDocuments>
			<robotsTxt ignore="true"/>
			<robotsMeta ignore="true"/>
			<sitemapResolver ignore="true"/>

			<recrawlableResolver class="com.norconex.collector.http.recrawl.impl.GenericRecrawlableResolver" sitemapSupport="last">
				<minFrequency applyTo="reference" value="3d">.*</minFrequency>
			</recrawlableResolver>

			<metadataFilters>
				<filter class="com.norconex.collector.core.filter.impl.MetadataFilter"
				        onMatch="include">
					<fieldMatcher ignoreCase="true">Content-Type</fieldMatcher>
					<valueMatcher method="regex" ignoreCase="true">.*(text/plain|text/htm|image|audio|video).*</valueMatcher>
				</filter>
			</metadataFilters>
			<referenceFilters>
				<filter class="com.norconex.collector.core.filter.impl.ReferenceFilter" onMatch="include">
					<valueMatcher method="regex">.*[\.\/]google.*com/</valueMatcher>
				</filter>
			</referenceFilters>
			<importer>
				<preParseHandlers>
					#parse("../shared/preParseHandlers.xml")
				</preParseHandlers>
				<documentParserFactory>
					#parse("../shared/documentParserFactory.xml")
				</documentParserFactory>
				<postParseHandlers>
					#parse("../shared/postParseHandlers.xml")
				</postParseHandlers>
			</importer>
			#parse("../shared/commiter-configs.xml")
			<httpFetchers>
				<fetcher class="com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher">
					<browser>firefox</browser>
					<remoteURL>http://selenium-hub:4444</remoteURL>
				</fetcher>
			</httpFetchers>
		</crawler>
	</crawlers>
	<crawlerDefaults>
		<numThreads>1</numThreads>
		<delay class="com.norconex.collector.http.delay.impl.GenericDelayResolver"
		       default="50" ignoreRobotsCrawlDelay="true" scope="site">
		</delay>
		<maxDepth>4</maxDepth>
		<orphansStrategy>DELETE</orphansStrategy>
		<keepDownloads>false</keepDownloads>
		<robotsTxt ignore="false"/> <!-- can be overwritten in the annotation file per job -->
		<robotsMeta ignore="false"/> <!-- can be overwritten in the annotation file per job -->
	</crawlerDefaults>
</httpcollector>
```

**Expected Behaviour**
URLs matching the metadataFilters criteria should be processed and committed.

**Actual Behavior**
The logs indicate URLs are rejected due to no "include" metadata filters matched, even though they should match the criteria set in metadataFilters.
**Output**
```
11:24:11.142 [www.google.com#1] INFO  REJECTED_FILTER - https://www.google.com/ - No "include" metadata filters matched.
11:24:11.177 [www.google.com#1] INFO  CrawlProgressLogger - 1(+1) processed | 0(+0) queued | 0 processed/sec | 31 seconds elapsed
11:24:11.182 [www.google.com] INFO  Crawler - Deleting orphan references (if any)...
11:24:11.182 [www.google.com#1] INFO  CRAWLER_RUN_THREAD_END - Thread[www.google.com#1,5,main]
11:24:11.183 [www.google.com#1] INFO  WebDriverHttpFetcher - Shutting down FIREFOX web driver.
11:24:11.212 [www.google.com] INFO  Crawler - Deleted 0 orphan references.
11:24:11.222 [www.google.com] INFO  CRAWLER_RUN_END - www.google.com
11:24:11.236 [www.google.com] INFO  Crawler - Crawler completed.
11:24:11.257 [www.google.com] INFO  Crawler - Execution Summary:
Total processed:   1
Since (re)start:
  Crawl duration:  31 seconds
  Avg. throughput: 0 processed/seconds
  Event counts:
    CRAWLER_RUN_BEGIN:         1
    CRAWLER_RUN_END:           1
    CRAWLER_RUN_THREAD_BEGIN:  1
    DOCUMENT_FETCHED:          1
    DOCUMENT_PROCESSED:        1
    DOCUMENT_QUEUED:           1
    REJECTED_FILTER:           12
    URLS_EXTRACTED:            1
11:24:11.271 [www.google.com] INFO  MVStoreDataStoreEngine - Closing data store engine...
11:24:11.272 [www.google.com] INFO  MVStoreDataStoreEngine - Compacting data store...
11:24:11.365 [www.google.com] INFO  MVStoreDataStoreEngine - Data store engine closed.
```
As you can see from the output, there was nothing to commit mainly because of the following message:
`11:24:11.142 [www.google.com#1] INFO  REJECTED_FILTER - https://www.google.com/ - No "include" metadata filters matched.`

**Investigation**

- When using firefox without Dockerization, got same result, i.e.
```
<httpFetchers>
  <fetcher class="com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher">
	  <browser>firefox</browser>
	  <driverPath>/opt/crawler/drivers/geckodriver</driverPath>
	  <browserPath>/usr/bin/firefox</browserPath>
  </fetcher>
</httpFetchers>
```

- When switching to GenericHttpFetcher, the issue does not occur, and documents are processed as expected. i.e.
```
<httpFetchers>
  <fetcher class="com.norconex.collector.http.fetch.impl.GenericHttpFetcher">
	  <cookieSpec>default</cookieSpec>
	  <sslProtocols>SSLv3, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3</sslProtocols>
	  <expectContinueEnabled>true</expectContinueEnabled>
	  <trustAllSSLCertificates>false</trustAllSSLCertificates>
	  <!-- Some websites replies FORBIDDEN, when 'Accept' header is not present -->
	  <headers>
		  <header name="Accept">*/*</header>
	  </headers>
	  <forceCharsetDetection>true</forceCharsetDetection>
	  <userAgent>HTTP-Collector</userAgent>
  </fetcher>
</httpFetchers>
```
I no longer get REJECTED_FILTER message and crawler output indicates that a document will be committed containing website information. 

**Output:**
```
Total processed:   1
Since (re)start:
  Crawl duration:  21 seconds
  Avg. throughput: 0 processed/seconds
  Event counts:
    COMMITTER_ACCEPT_YES:      1
    COMMITTER_UPSERT_BEGIN:    1
    COMMITTER_UPSERT_END:      1
    CRAWLER_RUN_BEGIN:         1
    CRAWLER_RUN_END:           1
    CRAWLER_RUN_THREAD_BEGIN:  1
    CRAWLER_RUN_THREAD_END:    1
    DOCUMENT_COMMITTED_UPSERT: 1
    DOCUMENT_FETCHED:          1
    DOCUMENT_IMPORTED:         1
    DOCUMENT_PROCESSED:        1
    DOCUMENT_QUEUED:           1
    IMPORTER_HANDLER_BEGIN:    44
    IMPORTER_HANDLER_END:      44
    IMPORTER_PARSER_BEGIN:     1
    IMPORTER_PARSER_END:       1
    REJECTED_FILTER:           10
    URLS_EXTRACTED:            1
11:19:52.701 [www.google.com] INFO  MVStoreDataStoreEngine - Closing data store engine...
11:19:52.702 [www.google.com] INFO  MVStoreDataStoreEngine - Compacting data store...
11:19:52.759 [www.google.com] INFO  MVStoreDataStoreEngine - Data store engine closed.
```
- No errors are visible in the crawler's output that would indicate a misconfiguration or exception.


Could this behavior be a bug related to WebDriverHttpFetcher, or am I missing a necessary configuration for metadataFilters to work correctly with it? Any guidance or suggestions for further troubleshooting would be greatly appreciated.

Thank you for your assistance.

**Comment by essiembre** [comment] 2024-02-13 14:55
Unless it has changed lately, Web Drivers do not make HTTP headers accessible, so metadata filters relying on those have nothing to work with.

To try to work around this limitation, you can configure the "httpSniffer" option.  More details here:  [WebDriverHttpFetcher](https://opensource.norconex.com/crawlers/web/v3/apidocs/com/norconex/collector/http/fetch/impl/webdriver/WebDriverHttpFetcher.html#nx-xml-usage-heading).

**Comment by gitter355** [comment] 2024-02-14 08:17
Configuring httpSniffer to include `Content-Type` header helped and now `metadataFilters` is working as expected.

Thank you!

**Comment by essiembre** [comment] 2024-02-14 08:19
Great! Thanks for confirming.

**Closed by essiembre** 2024-02-14 08:19 UTC
