### ISSUE TITLE
Potential issue with relational links

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#188] opened 2015-11-30 19:30 UTC
A site has a page with url ```http://www.site.com/en/articles/articles.html?param.....``` with relational links looking like ```<a href="/en/articles/detail/article-x.html"> .... ```

When I click the link the browser goes to ```http://www.site.com/en/articles/detail/article-x.html```, and when I trying to crawl the page by the collector, it tries to follow such link: ```http://www.site.com/en/articles/en/articles/detail/article-x.html```, which, of course, delivers 404.

I'm not sure is the behaviour correct.

**Comment by essiembre** [comment] 2015-12-02 21:08
Can you specify the exact page URL?  I have tried the scenario you describe in a small test and it worked just fine.  I suspect one of the relative URLs in the page itself is wrong.  Having access to that page would allow me to confirm.  Thank you.

**Comment by AntonioAmore** [comment] 2015-12-03 18:07
Here it is:
```
http://www.vig.com/en/press/press-releases.html?send=Show&tx_ttnews[catSel][]=&tx_ttnews[month]=&tx_ttnews[showCZ]=0&tx_ttnews[year]=2009
```

**Comment by essiembre** [comment] 2015-12-05 03:04
I found the cause.  It looks like the default link extractor does not handle the ``<base href="..." />`` tag.  This means all relative URLs are resolved to the last segment of your URL, as it would normally do it when no ``<base href="..." />`` is present.  This will need to be fixed.  

In the meantime, you can use the an alternative link extractor that should work just fine (I tested your page with it):
```xml
<linkExtractors>
  <extractor class="com.norconex.collector.http.url.impl.TikaLinkExtractor" />
</linkExtractors>
```

**Comment by AntonioAmore** [comment] 2015-12-05 12:24
This solution works perfectly in my case, thank you.

**Comment by essiembre** [comment] 2015-12-09 03:39
The default link extractor, [GenericLinkExtractor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericLinkExtractor.html), now supports the base href tag.  Feel free to try the [latest snapshot](https://www.norconex.com/collectors/collector-http/download) and revert back to the default if you want to benefit from the extra features the generic link extractor brings (it is also faster than the Tika one).

**Comment by AntonioAmore** [comment] 2015-12-09 16:57
Thanks for your help!

**Comment by essiembre** [comment] 2015-12-09 21:37
I am closing assuming you meant it worked for you.  If you run into that same issue again with it, please re-open.

**Closed by essiembre** 2015-12-09 21:37 UTC
Labels: bug, fixed/done
