### ISSUE TITLE
All documents removed when startURL is not ready to be recrawled

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#278] opened 2016-07-18 16:25 UTC
StartURL is REJECTED_PREMATURE and because of this all references are deleted (because  orphanStrategy is set to DELETE maybe). Not the behavior I expect.

Also the recrawl time was set to DAILY. I think it uses 24h, but would make more sense to me if it just checked if the crawldate is same day.

**Comment by essiembre** [comment] 2016-07-18 16:42
What do you mean by "reference are deleted"?  Is the "remove" method called on your committer for all these references?  Make sure you rely on committers to deal with your crawled content, not the crawl store.  If you have set the orphan strategy to delete, then it may be why, try changing it.  In any case, a "premature" URL should not trigger a call to the remove method of your Committer.  Let me know if that's what it does and please attach the necessary to reproduce.

For daily, we do not plan to change it since the next day may be only a few hours after initial crawl. With 24h, we have the guarantee you'll crawl a page "at most" once a day.   If this causes you problem, we can make it a feature request to support an alternative approach.

**Comment by essiembre** [comment] 2016-07-26 17:45
The explanation for this one is very similar to #274.  A document that is not ready to be re-crawled will not be parsed to extract its links, so children that are normally "followed" are not in this case.  Then the crawler relies on what is in the cache (orphans) and process them according to your orphan strategy.  You have yours at "DELETE".  Changing it to "PROCESS" will resolve your issue.

This is a rather tricky situation where "orphans" can mean a few different things. In its true sense, "orphan" should probably mean pages no longer linked from anywhere.  But in the current case, pages that are "skipped" before URLs are extracted (unmodified based on HTTP header, or premature) will likely see their children also considered "orphans" (unreachable), unless they are also linked from other pages being crawled.    

To make the distinction, we would have to store in the crawl store (cache) all extracted links for every page, effectively exploding its current size.  When a page then gets skipped (as opposed to a true rejection), all its previously extracted URLs should be loaded from cache and followed as if the original page was crawled.  This would ensure what remains in the cache at the very end are truly orphans (unreachable).  The downside is the potential performance impact of having a much bigger crawl store.  

Maybe this could be made optional by a configuration setting that defines what should be considered orphans and only cache all child URLs if explicitly configured to do so?

Any thoughts on this?  Do you have a better idea?

**Comment by OkkeKlein** [comment] 2016-08-07 14:51
Tricky indeed. But when skipping a URL they should get a different status from unreachable URL's. Which would enable the orphan finder to process them differently. 

Also, having all links that refer to a page stored makes it also possible to count them and give them more "weight". A very crude way, but could increase relevance for search.

**Comment by essiembre** [comment] 2016-08-16 02:42
The [latest snapshot](http://www.norconex.com/collectors/collector-http/download) now has a fix for this.  Now extracted URLs are stored in the URL store so they will be readily available for re-crawl when a "valid" document is skipped before its URL could be extracted. I am hoping the performance impact of storing much more information in the crawl store will not be noticeable.  I suspect it should not make any difference unless for very aggressive crawlers (e.g. zero delays between hits and many threads). 

Make sure you start with a fresh crawl to take advantage of this fix and please let me know how that goes for you.

**Comment by OkkeKlein** [comment] 2016-08-18 13:57
First tests look good. Document are recrawled. MongoDB size is about 18MB for 7000 documents, so not a problem.

**Comment by essiembre** [comment] 2016-08-18 16:31
Great, thanks for confirming!

**Closed by essiembre** 2016-08-18 16:31 UTC
Labels: bug, fixed/done
