### ISSUE TITLE
Canonical links not detected

### ISSUE THREAD

**Issue by Nycander** [Norconex/collector-http#115] opened 2015-06-03 07:57 UTC
This URL fails to detect canonical urls: http://www.folksam.se/forsakringar/djurforsakring/kattforsakring
Seems as if the link tag is hidden behind tags inside javascript code.

I also saw that the current code uses regular expressions: http://stackoverflow.com/a/1732454/191967
That method is known to be error prone, and I think this is showing here.

My current workaround is a jsoup implementation of ICanonicalLinkDetector:

    @Override
    public String detectFromContent(String reference,
            InputStream is,
            ContentType contentType) throws IOException {

        ContentType[] cTypes = contentTypes;
        if (ArrayUtils.isEmpty(cTypes)) {
            cTypes = DEFAULT_CONTENT_TYPES;
        }

        // Do not extract if not a supported content type
        if (!ArrayUtils.contains(cTypes, contentType)) {
            return null;
        }

        Document document = Jsoup.parse(is, "UTF-8", reference);
        Elements elements = document.select("link[rel=canonical]");
        if (elements.isEmpty()) {
            return null;
        }
        String href = elements.first().attr("href");
        if (! href.isEmpty()) {
            return toAbsolute(reference, href);
        }
        return null;
    }

**Comment by essiembre** [comment] 2015-06-04 17:24
I found the cause in the regex code.  The fix will be in the next snapshot release.

I think we are matching more than we are parsing with this one (the debate in the link you provide revolves around "parsing") as we do not need XML parts/structure for anything, we just want to detect a URL. It maybe more difficult to nail right sometimes with regex, but it is the best choice here for other considerations.

Performance-wise, the overhead of converting HTML to clean XML, then loading the entire DOM tree into memory just to retrieve a URL, if present, has a cost. The current regex code is roughly 10 times faster than the implementation you provide, which is quite significant. The difference is higher on bigger/more complex pages.  When crawling millions, it quickly adds up.

Memory-wise, we cannot predict up-front the size of HTML pages crawled. Even if rare, there are huge HTML files out there.  In an effort to preserve memory in an multi-threaded crawl (where multiple HTMLs can be processed at once), the regex solution only reads small chunks of the file at a time (broken up wisely).  No matter the file size, you'll never need a lot of memory (or run out) just to detect a canonical URL.  The same cannot be said of a Jsoup/DOM approach which reads each documents entirely and stores it all into memory.

These are the reasons for consciously choosing regex to extract URLs and the reason why regex will stay. But of course, you are welcome to create and use your own ``ICanonicalLinkDetector`` implementation (that's the beauty of using an extensible solution).  :-)

**Comment by essiembre** [comment] 2015-06-04 22:45
The fix now is in the [latest snapshot](http://www.norconex.com/collectors/collector-http/download).

**Comment by essiembre** [comment] 2015-07-22 18:46
Norconex HTTP Collector 2.2.0 official release is out. It includes this fix. You can download it [here](http://www.norconex.com/collectors/collector-http/download).

**Closed by essiembre** 2015-07-22 18:46 UTC
Labels: bug, fixed/done
