### ISSUE TITLE
Is it possible to run WebDriverHttpFetcher on a headless linux server?

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#731] opened 2021-01-20 09:20 UTC
I have a setup working on Windows but can't get it to work on Ubuntu.

I tried to mimic X server on an Ubuntu server with xvfb, but that didn't work.

Chrome and Firefox have an option to start headless. Is there a way to use this?

**Comment by essiembre** [comment] 2021-01-22 06:55
The code always request for it to be headless.  

I just tried crawling a site on Ubuntu 20.04.1 LTS with firefox webdriver and it worked just fine.  I used:

* Mozilla Firefox 84.0.2
* geckodriver-v0.29.0-linux64.tar.gz

Please share your config along with the versions for your OS, browser, webdriver.

**Comment by OkkeKlein** [comment] 2021-01-22 20:40
Ok. I did a lot of testing and at the end fired up a new server to see if I could get it working from scratch. To keep it simple I will stick to Firefox and geckodriver.

The old server keeps showing `Error: no DISPLAY environment variable specified` which led me down the rabbit hole using xvfb.
The new server after adding` <robotsTxt ignore="true" class="StandardRobotsTxtProvider"/>` seems to work. Both servers have export DISPLAY="".

Any suggestions? Else i will rebuild rest around the crawler.

**Comment by essiembre** [comment] 2021-01-23 04:42
Please share your config (with site URL), your version of Ubuntu, Gecko driver, and Firefox.

**Comment by OkkeKlein** [comment] 2021-01-23 16:54
OK. I got it working on old server now as well. The only thing I could replicate is that the path to firefox should not be `/usr/bin/firefox` but `/usr/lib/firefox/firefox`

I pasted a stack trace below that you might find interesting. If not feel free to ignore.

```
16:45:06.827 [Norconex Minimum Test Page] ERROR HttpFetchClient - Fetcher WebDriverHttpFetcher failed to execute request.
java.lang.NullPointerException: null
        at com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher.fetchDocumentContent(WebDriverHttpFetcher.java:342) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher.fetch(WebDriverHttpFetcher.java:319) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.fetch.HttpFetchClient.fetch(HttpFetchClient.java:101) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider.getRobotsTxt(StandardRobotsTxtProvider.java:99) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.pipeline.queue.HttpQueuePipeline.getRobotsTxt(HttpQueuePipeline.java:81) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.pipeline.queue.RobotsTxtFiltersStage.findRejectingRobotsFilter(RobotsTxtFiltersStage.java:72) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.pipeline.queue.RobotsTxtFiltersStage.executeStage(RobotsTxtFiltersStage.java:48) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.pipeline.queue.AbstractQueueStage.execute(AbstractQueueStage.java:31) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.pipeline.queue.AbstractQueueStage.execute(AbstractQueueStage.java:24) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:91) ~[norconex-commons-lang-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at com.norconex.collector.http.crawler.HttpCrawler.executeQueuePipeline(HttpCrawler.java:286) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLsRegular(HttpCrawler.java:179) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLs(HttpCrawler.java:166) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.http.crawler.HttpCrawler.prepareExecution(HttpCrawler.java:153) ~[norconex-collector-http-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at com.norconex.collector.core.crawler.Crawler.startExecution(Crawler.java:269) ~[norconex-collector-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at com.norconex.jef5.job.AbstractResumableJob.execute(AbstractResumableJob.java:49) ~[norconex-jef-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at com.norconex.jef5.suite.JobSuite.runJob(JobSuite.java:512) ~[norconex-jef-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at com.norconex.jef5.job.group.AsyncJobGroup.runJob(AsyncJobGroup.java:135) ~[norconex-jef-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at com.norconex.jef5.job.group.AsyncJobGroup.lambda$executeGroup$0(AsyncJobGroup.java:104) ~[norconex-jef-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
16:45:06.841 [Norconex Minimum Test Page] INFO  StandardRobotsTxtProvider - No robots.txt found for https://www.voordeelvloeren.nl/robots.txt. (0 - null)
```

**Comment by essiembre** [comment] 2021-01-28 06:36
Interesting, technically the NullPointerException should not occur unless you got another exception prior to that one.  In any case, I am glad you found the cause and I am now catching this issue and throwing a more meaningful message giving pointers to fix this (will be part of the next snapshot release).  

Thanks for reporting.

**Closed by essiembre** 2021-01-28 06:36 UTC

**Comment by essiembre** [comment] 2021-01-31 06:32
I finally was able to find the cause for the NullPointerException it is now fixed in the v3 snapshot release.
