### ISSUE TITLE
date meta-tag issue

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#205] opened 2015-12-27 20:31 UTC
hi Norconex team,

I'm not sure what package this issue is related to - collector or importer, so posting it here:

something strange happens with the `"date"` http-meta tag: its value gets multiplied, the crawlers current runtime gets added and it gets copied to a new `"Date"` field. E.g.:
source:
```html
<meta name="date" content="2015-01-28 10:26:27"/>
```
result:
```json
        "date": [
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "2015-01-28 10:26:27",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "2015-01-28 10:26:27",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "2015-01-28 10:26:27",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "2015-01-28 10:26:27",
          "Sun, 27 Dec 2015 19:59:23 GMT"
        ],
        "Date": [
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "2015-01-28 10:26:27",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "2015-01-28 10:26:27",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "2015-01-28 10:26:27",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "Sun, 27 Dec 2015 19:59:23 GMT",
          "2015-01-28 10:26:27",
          "Sun, 27 Dec 2015 19:59:23 GMT"
        ],
```
I'm using java version "1.7.0_80", collector version info:
```
INFO  [main] [AbstractCollector] Version: Norconex HTTP Collector 2.4.0-SNAPSHOT (Norconex Inc.)
INFO  [main] [AbstractCollector] Version: Norconex Collector Core 1.4.0-SNAPSHOT (Norconex Inc.)
INFO  [main] [AbstractCollector] Version: Norconex Importer 2.5.0-SNAPSHOT (Norconex Inc.)
INFO  [main] [AbstractCollector] Version: Norconex JEF 4.0.7 (Norconex Inc.)
INFO  [main] [AbstractCollector] Version: Norconex Committer Core 2.0.3 (Norconex Inc.)
INFO  [main] [AbstractCollector] Version: "SolrCommitter" version is undefined.
```

Expected behavior: to have as a result exactly the same single field/value as in the source :)
Thanks!

**Comment by essiembre** [comment] 2015-12-27 20:34
In order to reproduce, can you please share your config?

**Comment by jetnet** [comment] 2015-12-27 20:46
Hi Pascal,

the current config has become quite complex - with a lot of "includes". I can share it, no problem, but if I remember right, the issue can be reproduced with the "minimum-config.xml".
If you will not be able to reproduce with the default settings, I'll "merge" and paste the current config here.
Thank you for the prompt response!

**Comment by essiembre** [comment] 2015-12-27 20:49
This is with any site you try? Otherwise or can you supply your URL?  Having dates from HTTP header as well as in the page as a metadata tag is not uncommon.  Having it appear so many times is. I'll see if I can find something suspicious with the URL you give me.  In all cases, you can use the [ForceSingleValueTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ForceSingleValueTagger.html) to only keep one of these.

**Comment by jetnet** [comment] 2015-12-27 21:05
basically, it happened with any site I crawled, at the beginning I just used the `DeleteTagger` to get rid off the date/Date fields in order not to confuse the Solr :)
But now I'd like finally to sort that out.

an URL I'm indexing: `https://www.dslbank.de/unternehmen/karriere.html`

**Comment by jetnet** [comment] 2015-12-27 21:07
btw, the `ForceSingleValueTagger` would not work, as you can see - the first and the last values are not from the source...

**Comment by essiembre** [comment] 2015-12-27 21:54
That's interesting.  I have no idea looking at your sample page why they appear so many times!  Have you configured both ``metadataFetcher`` and a ``documentFetcher``? Maybe that is one cause (that maybe we should question).  While this gets investigated further, here are a couple things you can try in the meantime.  

First, you can try preventing mixing HTTP headers with document metadata. You can do so by specifying a header prefix of your choice on the metadata and document fetchers. E.g.: 

```xml
<metadataFetcher class="com.norconex.collector.http.fetch.impl.GenericMetadataFetcher" >
    <headersPrefix>meta-fetcher-header-</headersPrefix>
</metadataFetcher>
<documentFetcher class="com.norconex.collector.http.fetch.impl.GenericDocumentFetcher">
    <headersPrefix>document-fetcher-header-</headersPrefix>
</documentFetcher>
```
What you should be left with in the Date field should come from your HTML only.  You can use the ``ForceSingleValueTagger`` on it.

You can also force a format for each date value encountered and overwriting the date value each time instead of adding to it using the [DateFormatTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DateFormatTagger.html). Like this (not tested):
```xml
<tagger class="com.norconex.importer.handler.tagger.impl.DateFormatTagger"
    fromField="date" fromFormat="yyyy-MM-dd HH:mm:ss" toFormat="yyyy-MM-dd HH:mm:ss"
    keepBadDates="false" overwrite="true" >
</tagger>
```
Let me know if any of these work for you.

**Comment by jetnet** [comment] 2015-12-28 06:32
how could I forget about the HTTP response headers! Of course the `"Date"` field comes from there!
So, I've added the prefixes into the config:
```xml
    <metadataFetcher class="${metaFetcher}" >
      <headersPrefix>${httpMetaPrefix}</headersPrefix>
    </metadataFetcher>
    <metadataFetcher class="${docFetcher}" >
      <headersPrefix>${docMetaPrefix}</headersPrefix>
    </metadataFetcher>
```
unfortunately the mixed values are still there:
```json
        "http_meta.Date": [
          "Mon, 28 Dec 2015 06:13:00 GMT"
        ],
        "date": [
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "2015-01-28 10:26:27",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "2015-01-28 10:26:27",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "2015-01-28 10:26:27",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "2015-01-28 10:26:27"
        ],
        "Date": [
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "2015-01-28 10:26:27",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "2015-01-28 10:26:27",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "2015-01-28 10:26:27",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "Mon, 28 Dec 2015 06:13:00 GMT",
          "2015-01-28 10:26:27"
        ],
        "http_meta.Connection": [
          "Keep-Alive"
        ],
        "Connection": [
          "Keep-Alive"
        ],
```
The `"Connection"` http-response header is here as an example, that the `metadataFetcher` still keeps the original fields (I assumed, it would delete them).
Could you please clarify, what the `documentFetcher` exactly does? I couldn't find any new fields with its prefix.
Thanks!

**Comment by jetnet** [comment] 2015-12-28 06:45
So, I've just added to the `preParseHandler` the following:
```xml
  <tagger class="${DeleteTagger}">
      <fields>Date</fields>
  </tagger>
```
and got the "expected" result:
```json
        "http_meta.Date": [
          "Mon, 28 Dec 2015 06:35:21 GMT"
        ],
        "date": [
          "2015-01-28 10:26:27"
        ],
```

Now I can work with the `date` field :)
So, it seems the http-response `Date` header "confuses" somehow the import module...

**Comment by essiembre** [comment] 2015-12-28 19:53
Thanks for sharing your results. Your own solution seems the simplest of all! Since I have not had a chance to try it myself yet, I will leave this ticket open until I found the cause for the multiple appearances and why you did not see the prefix take effect for the document fetcher.  There might be a bug.

**Comment by essiembre** [comment] 2016-08-11 05:00
It turns out there was an issue with sometimes having wrongfully duplicated values in a field.  This was related to having different fields of the same name but using different character case.  For some reason this caused values to be duplicated a few times.  This has been fixed in a dependent library now included in HTTP Collector latest [snapshot release](https://www.norconex.com/collectors/collector-http/download).

Can you give it a try and tell if that makes a difference for you? Make sure you install fresh or keep only most recent jars.  You can still have multiple values sometimes because HTTP headers and document properties are using the same names for example, but that's not related to having many duplicates of the same values (and previously discussed solutions should help with this one).

Also note that [DateFormatTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DateFormatTagger.html) has been modified to now accept multiple "fromFormat".  It will try all formats provided until one matches (if any).

**Comment by essiembre** [comment] 2016-08-29 04:58
This feature is now part of 2.6.0.

**Closed by essiembre** 2016-08-29 04:58 UTC
Labels: bug, fixed/done
