### ISSUE TITLE
Can't move latest log to backup folder

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#96] opened 2015-04-25 19:14 UTC
Running the crawler in ```resume``` mode, I got the error and the run stopped:

![25-04-2015 20-00-37](https://cloud.githubusercontent.com/assets/10865115/7334050/3f438ec8-eb86-11e4-9116-aff5e2030622.jpg)

log..backup no contains the previous one
log..latest\log contains the previous one

progress..backup contains the previous one
progress..latest\status **is empty**, so JEF Monitor says the status is unkown

**Comment by OkkeKlein** [comment] 2015-04-26 08:41
Looks like a permission problem to me.

**Comment by csaezl** [comment] 2015-04-27 15:44
I run the collector twice before the third failed. In between nothing changed concerning folders nor permissions.

**Comment by csaezl** [comment] 2015-04-27 17:53
And with Windows Explorer I can copy files to the tarjet folder

**Comment by csaezl** [comment] 2015-05-04 16:04
I believe I have an idea about when it happens. I have a config file with 100 url to crawl. I run the config file just with 10 of them, just to test. The run ended. I deleted the 10 url and included another group of 20 url and run it with ```-a resume```. At the very beginning, I got the error reported.
I recovered the scenario after processing the first 10 URL and run the second 20 this time with ```-a start```. No error happened.

**Comment by essiembre** [comment] 2015-05-07 04:46
I cannot reproduce the issue.  Did you try with the latest 2.2.0 snapshot release? It fixes a bug introduced in 2.1.0 with the ``-a resume`` flag not starting properly.

**Comment by essiembre** [comment] 2015-09-06 03:26
Since it's been a few months without confirmation, I will assume using a more recent release fixed your problem.  Marking as fixed and closing.

**Closed by essiembre** 2015-09-06 03:26 UTC
Labels: bug, fixed/done
