### ISSUE TITLE
recrawlableResolver does not work as expected

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#741] opened 2021-03-18 20:30 UTC
hello Pascal,

some pages still being crawled despite `recrawlableResolver` policy, e.g.:
```
<recrawlableResolver class="com.norconex.collector.http.recrawl.impl.GenericRecrawlableResolver" sitemapSupport="last" >
                <minFrequency applyTo="reference" value="1d">.*</minFrequency>
</recrawlableResolver>
```

* start 1st crawl and check an URL
```
$ grep //schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/ latest/logs/schule.fragfinn.de.log
schule.fragfinn.de: 2021-03-18 21:16:36 INFO - DOCUMENT_METADATA_FETCHED: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:16:36 INFO -          DOCUMENT_FETCHED: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:16:36 INFO -       CREATED_ROBOTS_META: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:16:36 INFO -            URLS_EXTRACTED: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:16:37 INFO -         DOCUMENT_IMPORTED: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:16:37 INFO -    DOCUMENT_COMMITTED_ADD: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
```

* start 2nd crawl right after and check the same URL
```
$ grep //schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/ latest/logs/schule.fragfinn.de.log
schule.fragfinn.de: 2021-03-18 21:17:09 INFO -        REJECTED_PREMATURE: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:17:09 INFO - DOCUMENT_METADATA_FETCHED: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:17:10 INFO -          DOCUMENT_FETCHED: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:17:10 INFO -       CREATED_ROBOTS_META: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:17:10 INFO -            URLS_EXTRACTED: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:17:14 INFO -         DOCUMENT_IMPORTED: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
schule.fragfinn.de: 2021-03-18 21:17:14 INFO -    DOCUMENT_COMMITTED_ADD: https://schule.fragfinn.de/macht-mit-finns-freundin-braucht-einen-namen/
```

it rejected, but fetched and committed this URL.
Expected behaviour: do not process it after `REJECTED_PREMATURE`

Please let me know, if you need the whole config.
Thanks a lot!

**Comment by jetnet** [comment] 2021-03-19 09:51
I found the configuration part, which causes the issue. It's `TikaLinkExtractor` in the following snippet:
```
<linkExtractors>
        <!-- Tika link extractor fetches "alt" data from images -->
        <extractor class="com.norconex.collector.http.url.impl.TikaLinkExtractor" ignoreNofollow="false"/>
        <!-- GenericLinkExtractor used to extract links from the following tags -->
        <extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor">
              <tags>
                  <tag name="frame" attribute="src" />
                  <tag name="iframe" attribute="src" />
                  <tag name="meta" attribute="http-equiv" />
                  <tag name="script" attribute="src" />
              </tags>
        </extractor>
</linkExtractors>
```

Could you please take a look? Thanks!

**Comment by essiembre** [comment] 2021-03-22 06:01
Odd, technically, the link extraction should not occur on a premature document.  Can you please share a complete configuration that reproduces the issue?

**Comment by jetnet** [comment] 2021-03-22 10:21
here we go: https://0x0.st/-q8z.xml

**Comment by essiembre** [comment] 2021-03-23 03:40
Thanks for sharing your file.  I was able to reproduce the issue with it.  It was tied to pages containing links to self. Such links were added as a child link to process even if the "parent" (i.e., itself) was identified as premature.  I just made a new 2.x snapshot release with a fix for it.  Please confirm.

**Comment by jetnet** [comment] 2021-03-23 08:56
Thank you very much for the quick fix! Really appreciate that!

I just tested and noticed a new issue with the sitemap:

before:
```
schule.fragfinn.de: 2021-03-22 11:09:43 ERROR - Could not obtain sitemap: https://www.fragfinn.de/sitemap.xml.  Expected status code 200, but got 301
schule.fragfinn.de: 2021-03-22 11:09:43 ERROR - Could not obtain sitemap: https://schule.fragfinn.de/sitemap.xml.  Expected status code 200, but got 301
schule.fragfinn.de: 2021-03-22 11:09:43 INFO - Resolving sitemap: https://schule.fragfinn.de/sitemap_index.xml
schule.fragfinn.de: 2021-03-22 11:09:43 INFO - Resolving sitemap: https://schule.fragfinn.de/page-sitemap.xml
```

latest snapshot:
```
schule.fragfinn.de: 2021-03-23 09:47:37 ERROR - Could not obtain sitemap: https://www.fragfinn.de/sitemap.xml.  Expected status code 200, but got 301
schule.fragfinn.de: 2021-03-23 09:47:37 ERROR - Could not obtain sitemap: https://schule.fragfinn.de/sitemap.xml.  Expected status code 200, but got 301
schule.fragfinn.de: 2021-03-23 09:47:37 INFO - Resolving sitemap: https://schule.fragfinn.de/sitemap_index.xml
schule.fragfinn.de: 2021-03-23 09:47:37 ERROR - Cannot fetch sitemap: https://schule.fragfinn.de/sitemap_index.xml (java.lang.NullPointerException)
```

Looks like the latest snapshot cannot fetch the sitemap. Could you please take a look? Thanks a lot!

**Comment by essiembre** [comment] 2021-03-29 20:29
Since the sitemap issue is tracked in #738, I will close this one.

I am assuming the "premature" issues are fixed?  If not feel free to reopen or create a new ticket.

**Comment by essiembre** [comment] 2021-04-06 04:36
I just made a new snapshot with a fix.  I could not reproduce the issue with it.  Please confirm.

**Comment by jetnet** [comment] 2021-04-06 05:47
yes, the snapshot `norconex-collector-http-2.9.1-20210406.043458-18.zip` works as expected!
Thanks you very much!

**Closed** 2021-04-06 05:48 UTC
Labels: bug, fixed/done
