### ISSUE TITLE
Scheduling crawls

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#123] opened 2015-07-06 10:33 UTC
When using a bunch of crawlers (different configs) for 1 server you don't want to melt under crawl load. What is the best way to do this?

(I basically want to start all crawls in a collector installation and define a site delay in GenericDelayResolver)

**Comment by essiembre** [comment] 2015-07-13 20:34
If you have defined and running several Collectors with one or more crawlers each, no magic come to mind other than being careful when you run each.   If all delays together are not very aggressive, you should be fine.  Otherwise, here are a few ideas:

* For small crawl durations are relatively small, specify different start time in a crontab for each (or Windows Scheduled Tasks).
* For long-running crawls, specify different time of the day where each crawl is more aggressive (regardless of cronjob). For instance, let's say you have 24 crawlers, and you want each one to take turn in being more aggressive, you can give each a specific time for that.  Here is one that will run more aggressively between 1:00AM and 2:00AM:
```xml
  <delay class="com.norconex.collector.http.delay.impl.GenericDelayResolver"
          default="10000" 
          ignoreRobotsCrawlDelay="true"
          scope="crawler">
      <schedule time="from 1:00 to 2:00" >1000</schedule>
  </delay>
```

**Comment by essiembre** [comment] 2015-07-13 21:01
I just realized the [GenericDelayResolver Javadoc](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/delay/impl/GenericDelayResolver.html) did not specify how to specify the delay for each schedule.  I updated it.

**Comment by OkkeKlein** [comment] 2015-07-14 11:51
It would be a nice feature if you could regex a bunch of crawler configs as argument (-c site1*.xml) and they would run sequential.

**Comment by essiembre** [comment] 2015-07-15 21:01
I am assuming you mean "collector" configs (since we cannot pass crawler configs now)?

By design when using command-line we want that each collector is run in its own JVM to provide the desired isolation.  So the wildcard idea won't be built into the java app.

Command-line wildcards in arguments are typically resolved by the OS. So shell/batch scripting is what I would indicate here.

You simply need to wrap the ``collector-http.sh`` script with your own script that accepts wildcard arguments, and iterate through all those config files arguments, invoking ``collector-http.sh`` for each, sequentially.  I will do what you want, in addition to ensuring a new JVM is launched each time.

**Comment by OkkeKlein** [comment] 2015-07-16 08:40
Thanx for tip. I can do this with shell script.

**Closed** 2015-07-22 19:03 UTC
Labels: question
