### ISSUE TITLE
[2.8.1-SNAPSHOT] Ineffective Ajax crawling

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-http#491] opened 2018-05-28 08:15 UTC
Hi!

An Ajax crawl works well in HttpCollector 2.7.1 but not in 2.8.1-SNAPHSOT (0 accepted contents).

Tested Url :
https://cadres.apec.fr/home/mes-offres/recherche-des-offres-demploi/liste-des-offres-demploi.html?sortsType=DATE&sortsDirection=DESCENDING&nbParPage=50&typeAffichage=detaille&page=0&motsCles=carrefour

**Comment by essiembre** [comment] 2018-06-01 04:16
I can reproduce but I have not found the cause yet.  Marking as a bug.

**Comment by essiembre** [comment] 2021-10-01 01:24
The HTTP Collector version 3 relies on WebDrivers so you can crawl JavaScript-driven content using popular browsers (Chrome, Firefox, ...).   That should resolve any issues you may have had with PhantomJS.  PhantomJS is what version 2.x relies on, and it has been abandoned for a few years now.  Given all that, no fixes involving PhantomJS and the HTTP Collector v2.x will be applied.

**Closed by essiembre** 2021-10-01 01:24 UTC
Labels: bug

**Comment by sylvainroussy** [comment] 2022-02-01 08:57
Url is deprecated now, but works with Norconex 3.0 and Webdriver for close Url : https://www.apec.fr/candidat/recherche-emploi.html/emploi
